### ISSUE TITLE
in Speaker adaptation, the voice is not getting synthesized. Can anyone help me with it and what is minimum number of samples is requried?

### ISSUE THREAD

**Issue by navinthenapster** [r9y9/deepvoice3_pytorch#107]
Training to build custom dataset on top of pretrained LjSpeech model

**Comment by nmstoker** [comment]
It won't _guarantee_ an answer, but I would recommend a bit more relevant information than your included here. Specifically detailing:

- what you're seeing that indicates it has gone wrong
- what you did to get there
- and ideally some steps you've already tried to help diagnose the situation.

For people to help you, they will often be more motivated if you show some willingness to invest effort yourself
