### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by krajasekhar845** [r9y9/deepvoice3_pytorch#109]
Hi,
   In my case,  I get this error:
    Found GPU0 GeForce 920MX which is of cuda capability 5.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Los event path: log/deepvoice3_multispeaker_vctk_preset
0it [00:00, ?it/s]THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCTensorMathPairwise.cu line=102 error=8 : invalid device function

Traceback (most recent call last):
  File "train.py", line 947, in <module>
    train_seq2seq=train_seq2seq, train_postnet=train_postnet)
  File "train.py", line 629, in train
    target_lengths / (r * downsample_step),
RuntimeError: cuda runtime error (8) : invalid device function at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCTensorMathPairwise.cu:102

Please slove this error.

**Comment by r9y9** [comment]
You can find the answer in the error log. I'm closing this out.

```
Found GPU0 GeForce 920MX which is of cuda capability 5.0.
PyTorch no longer supports this GPU because it is too old.
```
