### ISSUE TITLE
how to identify the speakers?

### ISSUE THREAD

**Issue by gitathrun** [r9y9/deepvoice3_pytorch#110]
It is really amazing this model produces multiple-speaker features, but how do you identified those speakers?

I searched your repo and did not find any infomation about the speaker_id (the variable you use in _tts() method) correlated with specific speaker profile as your [demo](https://r9y9.github.io/deepvoice3_pytorch/) shows.
Is there any table that could show the profile such as:
speaker_id: 1
index: xxx
gender: f
age: xx
....

Any instruction about it?

**Comment by gitathrun** [comment]
[speaker-info.txt](https://github.com/r9y9/deepvoice3_pytorch/files/2347746/speaker-info.txt)
I think this is the file you mentioned in the README.md. 
Download the VCTK data and unzip it, shall see this file.

**Comment by nmstoker** [comment]
@gitathrun Yes, that's the file with the details you were after.
As you found the answer, you could close this now.

**Comment by mrgloom** [comment]
How it's mapped to `speaker_id` ? 
https://github.com/r9y9/deepvoice3_pytorch/blob/master/synthesis.py#L42
