### ISSUE TITLE
Questions regarding dataset creation

### ISSUE THREAD

**Issue by DonaldTsang** [r9y9/deepvoice3_pytorch#111]
Assume that we already have a person reading a 10 hour e-book, and I have both the ebook and the audiobook, how do I create a dataset for deepvoice3 to train?

**Comment by nshmyrev** [comment]
Align text to audio with https://github.com/lowerquality/gentle or https://github.com/readbeyond/aeneas and use the result for training.

**Comment by nshmyrev** [comment]
After alignment you create a preprocessor like https://github.com/r9y9/deepvoice3_pytorch/blob/master/ljspeech.py and start the training.

**Comment by G-Wang** [comment]
as @nshmyrev  said, you should format your data in the same folder layout as LJSpeech, which has a wavs folder, and a corresponding metadata.csv with each wav name and their text.

Then you can run the preprocessing and training step as if you had ljspeech, and pass the ebook data folder instead.

**Comment by mrgloom** [comment]
Here is a comment for gentle and vctk dataset
https://github.com/r9y9/deepvoice3_pytorch/tree/master/vctk_preprocess

What is specific for vctk dataset that gentle not working on it?

**Comment by mrgloom** [comment]
Seems here is an answer
https://github.com/r9y9/deepvoice3_pytorch/issues/16#issuecomment-354480069

**Comment by AbuKashan** [comment]
> Align text to audio with https://github.com/lowerquality/gentle or https://github.com/readbeyond/aeneas and use the result for training.

After Aligning the files, what should be the format or file structure for preprocessing?
