### ISSUE TITLE
Is the vocoder Griffinlim or WaveNet?

### ISSUE THREAD

**Issue by peter05010402** [r9y9/deepvoice3_pytorch#112]

**Comment by r9y9** [comment]
See

- https://github.com/r9y9/deepvoice3_pytorch/blob/0b89c10cb473e032641c05cb8b105358c26c02b5/audio.py#L37-L43
- https://github.com/Jonathan-LeRoux/lws

**Comment by peter05010402** [comment]
Thank you @r9y9

**Comment by CathyW77** [comment]
> Thank you @r9y9

Does it mean the vododer is 'lws'?
