### ISSUE TITLE
Try large FFT size

### ISSUE THREAD

**Issue by r9y9** [r9y9/deepvoice3_pytorch#12]
addresses https://github.com/r9y9/deepvoice3_pytorch/issues/1#issuecomment-346924858

**Comment by dengbingfeng** [comment]
I have a try large fft size 2048  with the same param of 1024,  but didn't get good result.  Could you give me some suggestions which params you think may effect the result?

**Comment by r9y9** [comment]
More channels? https://github.com/r9y9/deepvoice3_pytorch/blob/e513a76b395af31b3436c784ae526e976e3566db/hparams.py#L132-L135

From my experience, `converter_channels` is one of the most important parameter that affects speech quality.
