### ISSUE TITLE
ignore_recognition_level?

### ISSUE THREAD

**Issue by kkokdari** [r9y9/deepvoice3_pytorch#124]
1. What is the relationship between the hparam 'ignore_recognition_level' and input text?
2. If we have this kind of json files, 
{
  "/home/ryuichi/Dropbox/sp/deepvoice3_pytorch/foobar/LJ001-0002.wav": "/home/ryuichi/Dropbox/sp/deepvoice3_pytorch/foobar/LJ001-0002.txt",
  "/home/ryuichi/Dropbox/sp/deepvoice3_pytorch/foobar/LJ001-0001.wav": "/home/ryuichi/Dropbox/sp/deepvoice3_pytorch/foobar/LJ001-0001.txt",
  "/home/ryuichi/Dropbox/sp/deepvoice3_pytorch/foobar/LJ001-0003.wav": "/home/ryuichi/Dropbox/sp/deepvoice3_pytorch/foobar/LJ001-0003.txt"
}
json_meta.py will save text's path in metadata, and write_metadata() will write text's path instead of text itself into train.txt. 

It seems that json_meta.py which is used to build custom dataset, can only deal with the jsons files like,
{
  "/home/ryuichi/Dropbox/sp/deepvoice3_pytorch/foobar/LJ001-0002.wav": "I've found the history in Issues!",
  "/home/ryuichi/Dropbox/sp/deepvoice3_pytorch/foobar/LJ001-0001.wav": "And there are some discussion about using aligned monophones as input, instead of text.",
  "/home/ryuichi/Dropbox/sp/deepvoice3_pytorch/foobar/LJ001-0003.wav": "But I didn't find the corresponding solution. Anyway, thank you for sharing your project!"
}

and actually, preprocess.py extract the acoustic features from wavs and use aligned labels to trim the silence(optionally). while text is processed in train.py before train(). So if we want to use mono phonemes instead of text as input, we need to modify the train.py, right?

**Comment by kkokdari** [comment]
@engiecat @r9y9 thank you for sharing and look forward to hearing from you

**Comment by engiecat** [comment]
@kkokdari 
hi! sorry for late reply(i am currently in hospital :/ )

basically ignore_recognition_level was implemented to be compatible with other similar github repos - https://github.com/carpedm20/multi-speaker-tacotron-tensorflow 

basically it is used for automatic transcript-audio aligning program in it.
(Json form generated from the program can be classified into-
"filename":"transcript" - well aligned transcript
"filename":["voice recognized text", "closest transcript"] - aligned transcript with not enough similarity with the voice recognized text
"filename":["text"] - couldnt even find candidate algnment)

the parameter determines whether to use the second case and the third case.

**Comment by kkokdari** [comment]
@engiecat 
Thank you for your reply! So here the "aligned" means "exactly what the speech is saying", but not "viterbi force alignment results", right?
Wish you recover soon!!!

**Comment by engiecat** [comment]
no no its the opposite

voice recognized text is the stt result
and aligned text is the text extracted from the transcript using the algorithm. (that matches stt result with the transcript)

thank you🤗🤗
