### ISSUE TITLE
Module ".version" is excluded by gitignore but imported in deepvoice init, throwing an error

### ISSUE THREAD

**Issue by Martin-Laclaustra** [r9y9/deepvoice3_pytorch#125]
I get this error unless I comment out this line in:
https://github.com/r9y9/deepvoice3_pytorch/blob/ed9003b2b5b001a39e9ecb25dbb158bd1a92d192/deepvoice3_pytorch/__init__.py#L3

```
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    from deepvoice3_pytorch import frontend, builder
  File "~/r9y9_deepvoice3_pytorch/deepvoice3_pytorch/__init__.py", line 3, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'deepvoice3_pytorch.version'
```

The module is in @r9y9 local dir, but not synced with github because that directory or file is listed in gitignore.
Should that line be commented or deleted?

**Comment by r9y9** [comment]
Please follow the installation guide: https://github.com/r9y9/deepvoice3_pytorch#installation

version.py should be created by `python setup.py develop` or equivalent.

https://github.com/r9y9/deepvoice3_pytorch/blob/ed9003b2b5b001a39e9ecb25dbb158bd1a92d192/setup.py#L27-L39

**Comment by mrgloom** [comment]
`pip install -e ".[bin]"` helped.

**Comment by mrgloom** [comment]
What is the difference with `python setup.py develop` ?
