### ISSUE TITLE
How much training data and how long of audio clip you need to train for a new person's voice? 

### ISSUE THREAD

**Issue by raynor08** [r9y9/deepvoice3_pytorch#126]
Hi @r9y9 ,  I'm trying to train the model using pre-trained weights and with new person's voice (Not from the multi-speaker dataset),  I wonder what's the minimum requirement for the new audio clip(s)? How much data and how long of the audio clip do I need,  what pre-processing should be done to the audio clips? 

Thank you

**Comment by G-Wang** [comment]
see here: https://github.com/r9y9/deepvoice3_pytorch/issues/89
