### ISSUE TITLE
Unable to synthesize from checkpoint, train model using LJSpeech data?

### ISSUE THREAD

**Issue by Pydataman** [r9y9/deepvoice3_pytorch#134]
python3 synthesis.py ./checkpoints/checkpoint_step001630000.pth ./test_list.txt ./result/

error:
File "synthesis.py", line 127, in <module>
    model.load_state_dict(checkpoint["state_dict"])
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MultiSpeakerTTSModel:
	Unexpected key(s) in state_dict: "seq2seq.decoder.attention.0.key_projection.bias", "seq2seq.decoder.attention.0.key_projection.weight_g", "seq2seq.decoder.attention.0.key_projection.weight_v", "seq2seq.decoder.attention.0.value_projection.bias", "seq2seq.decoder.attention.0.value_projection.weight_g", "seq2seq.decoder.attention.0.value_projection.weight_v", "seq2seq.decoder.attention.4.key_projection.bias", "seq2seq.decoder.attention.4.key_projection.weight_g", "seq2seq.decoder.attention.4.key_projection.weight_v", "seq2seq.decoder.attention.4.value_projection.bias", "seq2seq.decoder.attention.4.value_projection.weight_g", "seq2seq.decoder.attention.4.value_projection.weight_v". 
	size mismatch for seq2seq.encoder.embed_tokens.weight: copying a param with shape torch.Size([149, 256]) from checkpoint, the shape in current model is torch.Size([149, 128]).
	size mismatch for seq2seq.encoder.convolutions.0.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).

**Comment by G-Wang** [comment]
you checkpoint model is not the same as the one built when you run `synthesis.py`, make sure you pass the correct preset json for synthesis, so that the encoder/decoder/converter, etc sizes are consistent for training and synthesis. e.g 
`python synthesis.py --preset=20180505_deepvoice3_ljspeech.json \
  20180505_deepvoice3_checkpoint_step000640000.pth \
  sentences.txt \
  output_dir`

**Comment by shwetagargade216** [comment]
For the speaker adaption do we need multi-speaker data ?

**Comment by r9y9** [comment]
+1 for https://github.com/r9y9/deepvoice3_pytorch/issues/134#issuecomment-453650375

I will close the issue out. Feel free to reopen if the issue persists.

**Comment by CathyW77** [comment]
> you checkpoint model is not the same as the one built when you run `synthesis.py`, make sure you pass the correct preset json for synthesis, so that the encoder/decoder/converter, etc sizes are consistent for training and synthesis. e.g
> `python synthesis.py --preset=20180505_deepvoice3_ljspeech.json \ 20180505_deepvoice3_checkpoint_step000640000.pth \ sentences.txt \ output_dir`

I run this, but still went error! can you help me ?
