### ISSUE TITLE
how to use waveglow as vocoder? Do I need some post-processing?

### ISSUE THREAD

**Issue by mingboma** [r9y9/deepvoice3_pytorch#136]
I was trying almost a week to use waveglow or wavenet as vocoder, but it only generates pure noise. If I use griff-lim to generate the audios based on the mel-spectrogram, and I could get pretty good audio. Is there anything post-processing that I need to do before I feed the mel-spectrogram into waveglow or wavenet? 

I also tried to train with downsample_step = 4 and 1 and outputs_per_step= 4 and 1, but it still generates noise. 

The waveglow part works fines if I use tacotron2 (https://github.com/NVIDIA/tacotron2), and I also compared the fft_size, hop_size,fmax,fmin and sample_rate, these parameters in deepvoice3 are the same with tacotron2. But tacotron2 can generate very good audio while deepvoice3 can not. 

Is there any post-processing that I missed?

Many thanks!

**Comment by G-Wang** [comment]
You should look at the 'audio.py' file to make sure melspectrogram is computed the exactly same way. For example deepvoice uses lws for computing stft, which may not be the case for the other repo. Also factors like preemphasis, rescaling will effect it, so you need to make sure that the audio functions are the same besides fft size, hop size and fmin/fmax
