### ISSUE TITLE
While doing Speaker Adaption got error in synthesising  

### ISSUE THREAD

**Issue by shwetagargade216** [r9y9/deepvoice3_pytorch#138]
@r9y9 Thanks for the quick reply for previous question in issue-113 .

For synthesising on own data, I used your pre-trained model, and kept model for training, It's running since 2 hrs.  But while synthesising the updated checkpoints, I got below error.

I used command:
python synthesis.py --preset=presets/deepvoice3_ljspeech.json /pre/20180505_deepvoice3_checkpoint_step000640000.pth output/text_list.txt \ output 

Traceback (most recent call last):
  File "synthesis.py", line 127, in <module>
    model.load_state_dict(checkpoint["state_dict"])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MultiSpeakerTTSModel:
        Missing key(s) in state_dict: "seq2seq.decoder.attention.0.key_projection.bias", "seq2seq.decoder.attention.0.key_projection.weight_g", "seq2seq.decoder.attention.0.key_projection.weight_v", "seq2seq.decoder.attention.0.value_projection.bias", "seq2seq.decoder.attention.0.value_projection.weight_g", "seq2seq.decoder.attention.0.value_projection.weight_v", "seq2seq.decoder.attention.4.key_projection.bias", "seq2seq.decoder.attention.4.key_projection.weight_g", "seq2seq.decoder.attention.4.key_projection.weight_v", "seq2seq.decoder.attention.4.value_projection.bias", "seq2seq.decoder.attention.4.value_projection.weight_g", "seq2seq.decoder.attention.4.value_projection.weight_v". 
        size mismatch for seq2seq.encoder.embed_tokens.weight: copying a param with shape torch.Size([149, 128]) from checkpoint, the shape in current model is torch.Size([149, 256]).
        size mismatch for seq2seq.encoder.convolutions.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for seq2seq.encoder.convolutions.0.weight_g: copying a param with shape torch.Size([256, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.0.weight_v: copying a param with shape torch.Size([256, 128, 1]) from checkpoint, the shape in current model is torch.Size([512, 256, 1]).
        size mismatch for seq2seq.encoder.convolutions.2.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for seq2seq.encoder.convolutions.2.conv.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.2.conv.weight_v: copying a param with shape torch.Size([512, 256, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for seq2seq.encoder.convolutions.3.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for seq2seq.encoder.convolutions.3.conv.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.3.conv.weight_v: copying a param with shape torch.Size([512, 256, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for seq2seq.encoder.convolutions.4.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for seq2seq.encoder.convolutions.4.conv.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.4.conv.weight_v: copying a param with shape torch.Size([512, 256, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for seq2seq.encoder.convolutions.5.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for seq2seq.encoder.convolutions.5.conv.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.5.conv.weight_v: copying a param with shape torch.Size([512, 256, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for seq2seq.encoder.convolutions.6.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for seq2seq.encoder.convolutions.6.conv.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.6.conv.weight_v: copying a param with shape torch.Size([512, 256, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for seq2seq.encoder.convolutions.7.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for seq2seq.encoder.convolutions.7.conv.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.7.conv.weight_v: copying a param with shape torch.Size([512, 256, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for seq2seq.encoder.convolutions.8.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for seq2seq.encoder.convolutions.8.conv.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.8.conv.weight_v: copying a param with shape torch.Size([512, 256, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for seq2seq.encoder.convolutions.9.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for seq2seq.encoder.convolutions.9.conv.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.9.conv.weight_v: copying a param with shape torch.Size([512, 256, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for seq2seq.encoder.convolutions.10.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for seq2seq.encoder.convolutions.10.conv.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.10.conv.weight_v: copying a param with shape torch.Size([512, 256, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for seq2seq.encoder.convolutions.11.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for seq2seq.encoder.convolutions.11.conv.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.11.conv.weight_v: copying a param with shape torch.Size([512, 256, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for seq2seq.encoder.convolutions.12.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for seq2seq.encoder.convolutions.12.weight_g: copying a param with shape torch.Size([128, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 1, 1]).
        size mismatch for seq2seq.encoder.convolutions.12.weight_v: copying a param with shape torch.Size([128, 256, 1]) from checkpoint, the shape in current model is torch.Size([256, 512, 1]).
        size mismatch for seq2seq.decoder.embed_keys_positions.weight: copying a param with shape torch.Size([512, 128]) from checkpoint, the shape in current model is torch.Size([512, 256]).
        size mismatch for seq2seq.decoder.attention.0.query_projection.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for seq2seq.decoder.attention.0.query_projection.weight_g: copying a param with shape torch.Size([128, 1]) from checkpoint, the shape in current model is torch.Size([256, 1]).
        size mismatch for seq2seq.decoder.attention.0.query_projection.weight_v: copying a param with shape torch.Size([128, 256]) from checkpoint, the shape in current model is torch.Size([256, 256]).
        size mismatch for seq2seq.decoder.attention.0.out_projection.weight_v: copying a param with shape torch.Size([256, 128]) from checkpoint, the shape in current model is torch.Size([256, 256]).
        size mismatch for seq2seq.decoder.attention.4.query_projection.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for seq2seq.decoder.attention.4.query_projection.weight_g: copying a param with shape torch.Size([128, 1]) from checkpoint, the shape in current model is torch.Size([256, 1]).
        size mismatch for seq2seq.decoder.attention.4.query_projection.weight_v: copying a param with shape torch.Size([128, 256]) from checkpoint, the shape in current model is torch.Size([256, 256]).
        size mismatch for seq2seq.decoder.attention.4.out_projection.weight_v: copying a param with shape torch.Size([256, 128]) from checkpoint, the shape in current model is torch.Size([256, 256]).

**Comment by shwetagargade216** [comment]
Sorry my mistake, I removed --preset parameters. Thanks ... I'm closing this issues

**Comment by MyJumperBroke23** [comment]
> Sorry my mistake, I removed --preset parameters. Thanks ... I'm closing this issues

I'm having this same issue. What when you say you removed --preset parameters, does that mean that your command would look like

python synthesis.py /pre/20180505_deepvoice3_checkpoint_step000640000.pth output/text_list.txt \ output

**Comment by MyJumperBroke23** [comment]
@shwetagargade216

**Comment by shwetagargade216** [comment]
yeah. preset was not useful for me. 
simply use:
python synthesis.py /pre/20180505_deepvoice3_checkpoint_step000640000.pth output/text_list.txt output
means also remove ' \ ' such type of symbols.
