### ISSUE TITLE
Some modification on my side

### ISSUE THREAD

**Issue by bobosui** [r9y9/deepvoice3_pytorch#14]
1. deepvoice3_pytorch/__init__.py 
from .version import __version__
this line has error
version.py is not provided.

2. deepvoice3_pytorch/builder.py
deepvoice3_multispeaker
inconsistent with hparams.py

3. deepvoice3_pytorch/deepvoice3.py 
line 474, (done>0.5).all()
maybe done.data is better

**Comment by r9y9** [comment]
Thank you for your feedback. Comments follow:

> deepvoice3_pytorch/init.py
from .version import version
this line has error
version.py is not provided.

version.py is generated during installation process (`python setup.py develop`). See https://github.com/r9y9/deepvoice3_pytorch/blob/d990533df25055e660ab95bcd29394738934f793/setup.py#L31-L36

> deepvoice3_pytorch/builder.py
deepvoice3_multispeaker
inconsistent with hparams.py

Do you mean `deepvoice3_vctk` is better than `deepvoice3_multispeaker`? I choose `deepvoice3_multispeaker` for the builder name (not preset name) in case we can use multi-speaker dataset other than VCTK.

> deepvoice3_pytorch/deepvoice3.py
line 474, (done>0.5).all()
maybe done.data is better

I'm not sure if it makes any difference. Do you think it's better?

**Comment by bobosui** [comment]
Thanks for the quick feedback.
2. deepvoice3_pytorch/builder.py
It is not a big issue for me, I can change the hyper-parameters from "builder=deepvoice3_vctk" to "builder=deepvoice3_multispeaker" to fix it.

3. (done>0.5).all() 
I got an error message here. I guess this is probably because I am using a lower version of pytorch, since <done> is defined with Variable (which has no all() function in my pytorch version). 

Thank you very much！
