### ISSUE TITLE
pytorch combination

### ISSUE THREAD

**Issue by Tortoise17** [r9y9/deepvoice3_pytorch#143]
Dear Friends / 
I have one error. and I cannot resolve it as I am new in pytorch as well. 
while running the code, there is combination error of pytorch
If you can guide me what mistake I am making. 
my pytorch is 

$ python -c "import torch; print(torch.__version__)"
1.0.1.post2

Please help. Below is error which I am facing at last step.
Thank you so much for help in advance. 

Greetings.

-----------------------------------------------------------------------------------------------------------------------
****0 Scientists at the CERN laboratory say they have discovered a new particle.**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-9596b20ad86e> in <module>
     13 for idx, text in enumerate(texts):
     14   print(idx, text)
---> 15   tts(model, text, figures=False)

<ipython-input-7-8e2443758ed6> in tts(model, text, p, speaker_id, fast, figures)
      1 def tts(model, text, p=0, speaker_id=None, fast=True, figures=True):
      2   from synthesis import tts as _tts
----> 3   waveform, alignment, spectrogram, mel = _tts(model, text, p, speaker_id, fast)
      4   if figures:
      5       visualize(alignment, spectrogram)

~/deepvoice3_pytorch/synthesis.py in tts(model, text, p, speaker_id, fast)
     47         p (float) : Replace word to pronounciation if p > 0. Default is 0.
     48     """
---> 49     model = model.to(device)
     50     model.eval()
     51     if fast:

~/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py in to(self, *args, **kwargs)
    369         """
    370 
--> 371         device, dtype, non_blocking = torch._C._nn._parse_to(*args, **kwargs)
    372 
    373         if dtype is not None:

TypeError: to() received an invalid combination of arguments - got (device), but expected one of:
 * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy)
 * (torch.dtype dtype, bool non_blocking, bool copy)
 * (Tensor tensor, bool non_blocking, bool copy)**

**Comment by RamkishoreBandla** [comment]
did you resolve this error ?
