### ISSUE TITLE
How to do speaker adaption on pre-trained multi-speaker model

### ISSUE THREAD

**Issue by shwetagargade216** [r9y9/deepvoice3_pytorch#144]
Hello, @r9y9 
I would like to do speaker adaption on own data but using VCTK pre-trained model instead on LJspeech pre-trained model. 
Could you let me know steps.
I tried with deepvoice3_vctk.json but failed to run, so I used presets of deepvoice3_ljspeech.json
I followed following steps correct me if I'm wrong 
pre-process:
python preprocess.py --preset=presets/deepvoice3_ljspeech.json ljspeech /home/ubuntu/shweta/voice-cloning/deepvoice3_pytorch/amale/deevpv ./amale/deepv/ljspeech

training
python train.py --data-root=/amale/deepv/ljspeech --checkpoint-dir=checkpt/vctk  --preset=presets/deepvoice3_ljspeech.json  --log-event-path=log/vctk  --restore-parts="/pre/multi_deep/20171222_deepvoice3_vctk108_checkpoint_step000300000.pth" --speaker-id=0

**Comment by G-Wang** [comment]
The speaker adaptation steps are well documented on the readme page. Pls follow those instructions and do some investigation, or look through the code base.

As r9r9 has already kindly provided this wonderful repo (which I can see takes alot of work), I don't imagine he has any extensive time to dig into a problem unless you've found some serious breaking bug with the repo.

If you do make any investigations or code changes that can help everyone else, pls don't hesitate to add as pull request.

**Comment by Willy-NotSpe** [comment]
Hello,@shwetagargade216
Can you give some advice about speaker adaption on own data but using VCTK pre-trained model?
