### ISSUE TITLE
Robotic Voice

### ISSUE THREAD

**Issue by SibtainRazaJamali** [r9y9/deepvoice3_pytorch#145]
I am getting robotic effect in the generated voice. Is there any post processing step require to refine the output wave file to sound more like a human instead of machine?Any help would be appreciated

**Comment by mrgloom** [comment]
You can try Nyanko model, it produce more natural voice.

**Comment by mrgloom** [comment]
Also you can check other issues on vocoder alterntaives:
https://github.com/r9y9/deepvoice3_pytorch/search?q=Vocoder&type=Issues
