### ISSUE TITLE
What vocoder is used in synthesis.py by default?

### ISSUE THREAD

**Issue by mrgloom** [r9y9/deepvoice3_pytorch#146]
What vocoder is used in synthesis.py by default?

**Comment by r9y9** [comment]
I'm not sure what you mean by the vodoer, but here goes the code: https://github.com/r9y9/deepvoice3_pytorch/blob/6fb72bf7b7d53414493f1daeb215f2fb178fba78/audio.py#L37-L43

**Comment by BuaaAlban** [comment]
> I'm not sure what you mean by the vodoer, but here goes the code:
> 
> https://github.com/r9y9/deepvoice3_pytorch/blob/6fb72bf7b7d53414493f1daeb215f2fb178fba78/audio.py#L37-L43

It seems like LWS???
How to use wavenet as an vocoder?

**Comment by CathyW77** [comment]
what is lws? It means the default vocoder's name is "lws"?
