### ISSUE TITLE
outputs_per_step > 1 not working

### ISSUE THREAD

**Issue by ColdEyeLampr** [r9y9/deepvoice3_pytorch#147]
I tried to set outputs_per_step greater than 1, but found the following bugs:

(1) in deepvoice3_pytorch/deepvoice3.py line #288:

`
inputs = inputs.view(inputs.size(0), inputs.size(1) // self.r, -1)
`
it raises an error when inputs.size(1) is not a multiple of self.r:

`
RuntimeError: invalid argument 2: size '[16 x 27 x -1]' is invalid for input with 70400 elements at /Users/soumith/code/builder/wheel/pytorch-src/aten/src/TH/THStorage.cpp:80
`

(2) in train.py line #683:

`
linear_l1_loss, linear_binary_div = spec_loss( linear_outputs[:, :-r, :], y[:, r:, :], target_mask, ...
`  

The shapes of linear_outputs and y are different, it raises an error in the following step:

`
RuntimeError: The expanded size of the tensor (98) must match the existing size (198) at non-singleton dimension 1
`

This may caused by the postnet(Converter) which do not handle the outputs_per_step > 1 case.

**Comment by r9y9** [comment]
I don't have time to look into it right now but It should not be difficult to support more flexible outputs_per_step.
