### ISSUE TITLE
10 seconds

### ISSUE THREAD

**Issue by SibtainRazaJamali** [r9y9/deepvoice3_pytorch#148]
Why deep voice doesn't make longer wave files for duration greater than 10 seconds?

**Comment by r9y9** [comment]
I am not exactly sure what you mean, but https://github.com/r9y9/deepvoice3_pytorch/blob/6fb72bf7b7d53414493f1daeb215f2fb178fba78/deepvoice3_pytorch/deepvoice3.py#L269 might fix your concern perhaps.
