### ISSUE TITLE
Training Deepvoice for my language

### ISSUE THREAD

**Issue by Usama0121** [r9y9/deepvoice3_pytorch#149]
Hi,

Can I use deepvoice to train TTS for my own language(Urdu)? I have around 200 hours of multi speaker data available for Urdu.

Thanks

**Comment by r9y9** [comment]
Yes, you can. Please follows the README first and then write some code to support your dataset.

**Comment by greatforu** [comment]
> Yes, you can. Please follows the README first and then write some code to support your dataset.

where i have to change in code as I have made dataset as per VCTK recipe.
