### ISSUE TITLE
Number of steps / loss value?

### ISSUE THREAD

**Issue by mrgloom** [r9y9/deepvoice3_pytorch#153]
What is recommended number of steps / loss value to stop training?

As I understand for ljspeech dataset by default number of steps is 816 * 2000 = 1632000
https://github.com/r9y9/deepvoice3_pytorch/blob/master/hparams.py#L106
https://github.com/r9y9/deepvoice3_pytorch/blob/master/presets/deepvoice3_ljspeech.json#L55

**Comment by r9y9** [comment]
It really depends and there's no clear answer for this. From my experience, 100k or 50k for intelligible speech and 500k ~ 1000k for further quality up.
