### ISSUE TITLE
Missing keys & unexpected keys in state_dict when loading self trained model

### ISSUE THREAD

**Issue by mennatallah644** [r9y9/deepvoice3_pytorch#156]
when i try to synthesize using my adapted model i got this error 
i am using vctk dataset 
![error](https://user-images.githubusercontent.com/32370077/58986891-a1e2de00-87de-11e9-8bf6-6ea1f5295077.PNG)

**Comment by tripzero** [comment]
I'm getting the same error on master with the vctk dataset.  I only trained with one speaker_id.  Not sure if that matters...

**Comment by harirawat** [comment]
I am also getting the same error on running synthesis.py after training the model.
I ran the following command which resulted in the error.
```
python synthesis.py --hparams="builder=deepvoice3,preset=presets/deepvoice3_vctk.json" 20171222_deepvoice3_vctk108_checkpoint_step000300000.pth sentences.txt output_dir
```

**Comment by mennatallah644** [comment]
The error has gone when i ran this command
python synthesis.py --hparams="builder=deepvoice3_multispeaker,preset=deepvoice3_vctk" 20171222_deepvoice3_vctk108_checkpoint_step000300000.pth sentences.txt output_dir
