### ISSUE TITLE
VCTK alignment

### ISSUE THREAD

**Issue by maelp** [r9y9/deepvoice3_pytorch#16]
Hi @r9y9 you mention that aligning VCTK with gentle does not work, can you tell what is happening? is it the quality of the alignment, and how did you see it?

**Comment by r9y9** [comment]
I had three problems:

- Some words were not aligned correctly. There's not timing information for those words.
- Beginning/ending silences were not well recognized.
- Some phoneme were misrecognized as pause. Noticed only an utterance, though.

**Comment by Young-Sun** [comment]
Hello @r9y9 , I'm trying to get forced alignment for VCTK corpus your code. (time label data)
By the way, was there error message for misrecognized files or you checked all the results of aligned label manually?
Shortly, I have to check all the aligned label to check whether there is an error or not.
And is it possible to share your aligned label for VCTK?
