### ISSUE TITLE
Is it possible to adapt to a new speaker?

### ISSUE THREAD

**Issue by sdx0112** [r9y9/deepvoice3_pytorch#163]
If I have some audio files from a new speaker, how can I adapt to this speaker using pre-trained model?

**Comment by r9y9** [comment]
Please see https://github.com/r9y9/deepvoice3_pytorch#speaker-adaptation.

**Comment by sdx0112** [comment]
If I am not take it wrongly, your instruction is to adapt to VCTK speakers only. My question is to adapt to any arbitrary new speaker.

**Comment by r9y9** [comment]
Not limited to VCTK. You'd need to write some code depending on your dataset though. See ljspeech.py for example.
