### ISSUE TITLE
Getting usage: synthesis.py [options] <checkpoint> <text_list_file> <dst_dir> on running synthesis.py

### ISSUE THREAD

**Issue by harirawat** [r9y9/deepvoice3_pytorch#165]
I am running the synthesis.py file by with the following arguments.
```python synthesis.py 20171222_deepvoice3_vctk108_checkpoint_step000300000.pth sentences.txt output_dir --preset=presets\deepvoice3_vctk.json```

On running this, the following line is getting displayed and the program is getting stopped.
```usage: synthesis.py [options] <checkpoint> <text_list_file> <dst_dir>```

Can anyone tell me what I am doing wrong?

**Comment by harirawat** [comment]
I changed the line to the following.
```python synthesis.py --hparams="builder=deepvoice3,preset=presets/deepvoice3_vctk.json" ./20171222_deepvoice3_vctk108_checkpoint_step000300000.pth ./sentences.txt ./output_dir```

Now I am getting the following error.
```Command line args:
 {'--checkpoint-postnet': None,
 '--checkpoint-seq2seq': None,
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': 'builder=deepvoice3,preset=presets/deepvoice3_vctk.json',
 '--max-decoder-steps': '500',
 '--output-html': False,
 '--replace_pronunciation_prob': '0.0',
 '--speaker_id': None,
 '<checkpoint>': './20171222_deepvoice3_vctk108_checkpoint_step000300000.pth',
 '<dst_dir>': './output_dir',
 '<text_list_file>': './sentences.txt'}
Traceback (most recent call last):
  File "synthesis.py", line 114, in <module>
    hparams.parse(args["--hparams"])
  File "C:\Users\abc\Downloads\deepvoice3_pytorch-master\deepvoice3_pytorch-master\hparam_tf\hparam.py", line 543, in parse
    values_map = parse_values(values, type_map)
  File "C:\Users\abc\Downloads\deepvoice3_pytorch-master\deepvoice3_pytorch-master\hparam_tf\hparam.py", line 263, in parse_values
    raise ValueError('Unknown hyperparameter type for %s' % name)
ValueError: Unknown hyperparameter type for preset```

**Comment by YYYYWD** [comment]
@harirawat Could you help me how do you solve it？I meet the same problem.

**Comment by Gatta** [comment]
Could you help me.I keep getting errors using this running format
