### ISSUE TITLE
WORLD vocoder support

### ISSUE THREAD

**Issue by hash2430** [r9y9/deepvoice3_pytorch#166]
I have created a branch that supports WORLD vocoder.
https://github.com/hash2430/dv3_world
I might not make a pull request for a while since I have not started that branch from fork and I must go through some procedure to make a pull request. I don't want to go through that trouble not knowing if that pull request is going to be accepted by r9y9.
But in the meantime, anyone who's looking for WORLD vocoder support are welcome to browse my repository.

**Comment by r9y9** [comment]
Sorry for the late reply. Great work! Probably the easiest option is to maintain your repo separately, but I am willing to accept a PR and review changes (not sure how hard it is though). If it turns out it's difficult to merge, then how about adding a link to your repo in the README of my repo?

**Comment by hash2430** [comment]
I suppose adding link to my repo in your README would be the easiest way for both of us and those who are looking for WORLD support for DV3.
I have a couple of ways in mind to optimize the WORLD part of the converter and I don't want to bother you with PR everytime I optimize minor details.
Thanks!
