### ISSUE TITLE
 Mask tensor can take 0 and 1 values only at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpp:589

### ISSUE THREAD

**Issue by YYYYWD** [r9y9/deepvoice3_pytorch#172]
Could you help me how to deal with this problem that 
File "J:\voice clone\deepvoice3_pytorch\deepvoice3_pytorch\deepvoice3.py", line 150, in forward
    x.data.masked_fill_(mask, mask_value)
**RuntimeError: Mask tensor can take 0 and 1 values only at** **C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpp:589 **

@r9y9

**Comment by thoshith-s** [comment]
Change in deepvoice3_pytorch/modules.py
def get_mask_from_lengths(memory, memory_lengths):
    """Get mask tensor from list of length
    Args:
        memory: (batch, max_time, dim)
        memory_lengths: array like
    """
    mask = memory.data.new(memory.size(0), memory.size(1)).byte().zero_()
    for idx, l in enumerate(memory_lengths):
        mask[idx][:l] = 1
    **return ~ mask**

To

def get_mask_from_lengths(memory, memory_lengths):
    """Get mask tensor from list of length
    Args:
        memory: (batch, max_time, dim)
        memory_lengths: array like
    """
    mask = memory.data.new(memory.size(0), memory.size(1)).byte().zero_()
    for idx, l in enumerate(memory_lengths):
        mask[idx][:l] = 1
    **return mask^1**

**Comment by r9y9** [comment]
reopen

**Comment by r9y9** [comment]
I'm gonna disable stale bot. It isn't really helpful for me.
