### ISSUE TITLE
Low GPU memory utilization

### ISSUE THREAD

**Issue by fabio-costa-movile** [r9y9/deepvoice3_pytorch#174]
Hi!

I am training the LJSpeech dataset in a machine with 8 CPUs and one Tesla V100 GPU. However I can only use ~4GB of GPU memory, what seems like a waste in a 16GB Hardware. :-)

I tried with others GPU and seems the same thing

Any ideias?

**Comment by r9y9** [comment]
Try increasing batch size.

**Comment by fabio-costa-movile** [comment]
Hi! 

I increased batch size to 64 and now its using 10GB. I am a little worried about getting bad accuracy:

https://stats.stackexchange.com/questions/164876/tradeoff-batch-size-vs-number-of-iterations-to-train-a-neural-network

Should I be worried?
