### ISSUE TITLE
Can't fine model checkpoints

### ISSUE THREAD

**Issue by Arafat4341** [r9y9/deepvoice3_pytorch#182]
Model checkpoints (.pth) and alignments (.png) are supposed to be saved in
``./checkpoints`` directory per 5000 steps by default while training?
I don't find any. I tried to train model with jsut data

**Comment by r9y9** [comment]
https://github.com/r9y9/deepvoice3_pytorch/blob/897f31e57eb6ec2f0cafa8dc62968e60f6a96407/hparams.py#L112 As you can see in the hparams.py, checkpoints are supposed to be saved per 10000 steps by default.

**Comment by Arafat4341** [comment]
Okay. But there is no 

`checkpoints`

 directory created.

**Comment by r9y9** [comment]
No. You have wrong input arguments, thus you are seeing the `usage: train.py [options]`.

```
python train.py --data-root=jsut_op2/ --hparams="frontend=jp,builder=deepvoice3,preset=deepvoice3_ljspeech"
```

I guess this works. You need to merge two `--hparams=` into one.

**Comment by Arafat4341** [comment]
This worked..! But problem is: `raise ValueError('Unknown hyperparameter type for %s' % name)` occurs in hparam.py file.

**Comment by r9y9** [comment]
Ok, this should work:

```
python train.py --data-root=jsut_op2/ --hparams="frontend=jp,builder=deepvoice3" --preset ${your path to config.json}
```
