### ISSUE TITLE
'train.txt' is not generating in output directory after pre-processing

### ISSUE THREAD

**Issue by Arafat4341** [r9y9/deepvoice3_pytorch#183]
I used jsut data for training. The line I used for pre-processing: 
`python preprocess.py jsut jsut_ver1.1/ jsut_op2/`.
It worked correctly and I got extracted features (mel-spectrograms and linear spectrograms) in `jsut_op2/`. I got `jsut-mel-___.npy` and `jsut-spec-___.npy` files.

But during training I get this exception:
`File "train.py", line 106, in collect_files
    with open(meta, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'jsut_op2/train.txt'`

My question is: Is it supposed to create the 'train.txt' file during pre-processing?

**Comment by r9y9** [comment]
Yes

https://github.com/r9y9/deepvoice3_pytorch/blob/897f31e57eb6ec2f0cafa8dc62968e60f6a96407/preprocess.py#L27-L36

**Comment by Arafat4341** [comment]
Then Is my pre-processing command wrong?

`python preprocess.py jsut jsut_ver1.1/ jsut_op2/`
