### ISSUE TITLE
Size mismatch for seq2seq.encoder.embed_tokens.weight

### ISSUE THREAD

**Issue by Arafat4341** [r9y9/deepvoice3_pytorch#184]
Hi, My training was completed upto `checkpoint_step000100000.pth`. While synthesizing I get this error:

`size mismatch for seq2seq.encoder.embed_tokens.weight: copying a param with shape torch.Size([65535, 256]) from checkpoint, the shape in current model is torch.Size([149, 256])`.

I used jsut data and the line of code that I used for synthesizing:
`python synthesis.py checkpoints/checkpoint_step000100000.pth jptest.txt jptestop/ --preset=presets/deepvoice3_ljspeech.json`

Why am I getting this error?

**Comment by r9y9** [comment]
Same as https://github.com/r9y9/deepvoice3_pytorch/issues/134#issuecomment-453650375

If you work on jsut, `--preset=presets/deepvoice3_ljspeech.json` doesn't look right for me.

**Comment by Arafat4341** [comment]
I also removed the line and tried... But same error. Size mismatch. This time I get even more detailed mismatch error!

`size mismatch for seq2seq.encoder.embed_tokens.weight: copying a param with shape torch.Size([65535, 256]) from checkpoint, the shape in current model is torch.Size([149, 128]).
	size mismatch for seq2seq.encoder.convolutions.0.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for seq2seq.encoder.convolutions.0.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 1, 1]).
	size mismatch for seq2seq.encoder.convolutions.0.weight_v: copying a param with shape torch.Size([512, 256, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 1]).
	size mismatch for seq2seq.encoder.convolutions.2.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	`
...................................
.................................

It goes on!

**Comment by Arafat4341** [comment]
I found out that `--preset=presets/deepvoice3_nikls.json` solves this problem for jsut. I am going to close the issue! Thanks for your support! @r9y9

**Comment by Arafat4341** [comment]
As I mentioned earlier, my training was completed upto checkpoint_step000100000.pth, I am getting ridiculous result after synthesizing! 
How far the training was supposed to go? can you tell? @r9y9
