### ISSUE TITLE
Problems with "present" parameter while working with JSUT

### ISSUE THREAD

**Issue by Arafat4341** [r9y9/deepvoice3_pytorch#185]
I've been facing problems with the `--present` parameter. There is no precise instruction regarding this parameter while working with jsut data in the wiki part. I just want to know what is the purpose of this parameter what value should I put in preprocess, train and synthesize commands. 
Thanks in advance!

**Comment by r9y9** [comment]
There's no `--present` parameter in the codebase. https://github.com/r9y9/deepvoice3_pytorch/search?q=present&unscoped_q=present

I guess you meant `--preset` parameter.

**Comment by Arafat4341** [comment]
@r9y9 Sorry for mistake. yes I meant --preset. What should be it's value in preprocess, train and synthesize commands while working with JSUT? Can you tell?
