### ISSUE TITLE
Resume training from previously saved checkpoint

### ISSUE THREAD

**Issue by Arafat4341** [r9y9/deepvoice3_pytorch#186]
How can I resume training from previously saved checkpoint.

Previously my model training was completed upto step 100000 ( `checkpoint_step000100000.pth`). Now I want to resume training from this step. How can I do this?? 
Please help!

**Comment by r9y9** [comment]
You can use `--checkpoint $path` option. See code for more details: https://github.com/r9y9/deepvoice3_pytorch/blob/897f31e57eb6ec2f0cafa8dc62968e60f6a96407/train.py#L1-L21
