### ISSUE TITLE
Huge qualitative difference between training time synthesize and Custom text synthesize

### ISSUE THREAD

**Issue by Arafat4341** [r9y9/deepvoice3_pytorch#188]
Hello! I am working with jsut. Model generates synthesized audio after every 10,000 steps of checkpoint. But when I try to synthesize my own text with that particular checkpoint, I see a huge qualitative difference. Infact the custom synthesized audio is no where near the the training time generated audio in terms of quality. 
Why does this happen? And what is that audio that is generated during training time?

**Comment by JohnHerry** [comment]
me too!
