### ISSUE TITLE
positional encoding

### ISSUE THREAD

**Issue by taras-sereda** [r9y9/deepvoice3_pytorch#19]
```
    position_enc = np.array([
        [position_rate * pos / np.power(10000, 2 * (i // 2) / d_pos_vec) for i in range(d_pos_vec)]
        if pos != 0 else np.zeros(d_pos_vec) for pos in range(n_position)])
```
Hey! I wonder what is a motivation behind repeating positional encoding values twice? 
in paper it's done this way:
```
position_rate * pos / np.power(10000,  i / d_pos_vec)...
```

**Comment by r9y9** [comment]
Sorry, I'm not sure what you mean by repeating twice. In paper, 

- `sin(position_rate * pos / np.power(10000, i / d_pos_vec)` (for even `i`)
- `cos(position_rate * pos / np.power(10000, i / d_pos_vec)` (for odd `i`)

The strategy in the code is that computing `position_rate * pos / np.power(10000, 2 * (i // 2) / d_pos_vec)` (eq. 1) for each `i` and `pos` and then slicing them with stride 2 as:

```
position_enc[1:, 0::2] = torch.sin(position_enc[1:, 0::2])  # dim 2i
position_enc[1:, 1::2] = torch.cos(position_enc[1:, 1::2])  # dim 2i+1
```

**Comment by taras-sereda** [comment]
the strategy is clear. 
even values in your code are correct, when odd values are wrong
```
d_pos_vec = 256
position_rate = 1.0
pos = 1
positions = [position_rate * pos / np.power(10000, 2 * (i//2) / d_pos_vec) for i in range(d_pos_vec)]
positions[0::2] = np.sin(positions[0::2])
positions[1::2] = np.cos(positions[1::2])
print(positions[:4])
[0.8414709848078965, 0.54030230586813977, 0.80196179521478528, 0.59737532508120794]
```
approach from paper
```
d_pos_vec = 256
position_rate = 1.0
pos = 1
i = 3
print(np.sin(position_rate * pos / np.power(10000, 0 / d_pos_vec)))
print(np.cos(position_rate * pos / np.power(10000, 1 / d_pos_vec)))
print(np.sin(position_rate * pos / np.power(10000, 2 / d_pos_vec)))
print(np.cos(position_rate * pos / np.power(10000, 3 / d_pos_vec)))
0.841470984808
0.569695008693
0.801961795215
0.623420035442
```
the results should be same. Do you agree?

**Comment by r9y9** [comment]
I see, you are right. Thank you for catching this. The implementation was actually adapted from https://github.com/jadore801120/attention-is-all-you-need-pytorch. I'm not sure the difference affects speech quality.

**Comment by taras-sereda** [comment]
@r9y9  you are welcome. 
I'm not sure as well if it affects the speech quality. Just wanted to clarify.
btw. have you tried to use self-attention idea from attention-is-all-you-need-pytorch?
It's in my list to try it in encoder part of the deepvoice3.

**Comment by r9y9** [comment]
I haven't tried it yet. If you get an impressive result with it, that would be great!

**Comment by taras-sereda** [comment]
https://github.com/r9y9/deepvoice3_pytorch/pull/20

**Comment by tuan3w** [comment]
I think the original  implementation is right (see [paper](https://arxiv.org/pdf/1706.03762.pdf)). `i` is the dimension index, not the position of word. `PE(pos, 2i)` and `PE(pos, 2i+1)` are the basis of space (like in FFT transformation). This allows learn attend by relative position: [See](https://www.reddit.com/r/MachineLearning/comments/6jdi87/r_question_about_positional_encodings_used_in/djdny8i/)

**Comment by r9y9** [comment]
@tuan3w Thank you for the explanation. For your information, assuming DeepVoice3 paper is correct, @taras-sereda is right. However, it makes more sense as you pointed out to design positional encoding `PE(pos+k, 2i)` can be represented as a linear combination of `PE(pos, 2i)` and `PE(pos, 2i+1)` for any fixed `k`.  I understand this allows learn attend by relative position.

@taras-sereda, what do you think?

**Comment by taras-sereda** [comment]
@r9y9 the justification provided by @tuan3w is convincing in favour of approach described in Attention is All you need paper. But clearly pos encoding described in DeepVoice3 paper is different. I'm not sure it makes much difference which one to use. Considering the fact that learnable positional encoding (which assumes no analytical representation) gives similar results. 
https://arxiv.org/pdf/1706.03762.pdf `Table 3 row(E)`

**Comment by r9y9** [comment]
@taras-sereda While I don't fully understand why DeepVoice3 uses a slightly different version of positional encoding, personally, either is fine if it actually works. As you may notice, the code in the repository is not trying to replicate DeepVoice3 exactly, but try to build a good TTS based on ideas from DeepVoice3. I have been using https://arxiv.org/abs/1706.03762 style positional encoding (with position rate) so far and get reasonable results. So my question is, did you get a reasonable result with the modification?

**Comment by r9y9** [comment]
Reverted https://github.com/r9y9/deepvoice3_pytorch/commit/aeed2258a9b1111669a793ae161cfe0a7396fdf0 for now. Happy to reapply if this change actually works well.
