### ISSUE TITLE
Increasing Training steps

### ISSUE THREAD

**Issue by Arafat4341** [r9y9/deepvoice3_pytorch#190]
Hello!
How can I increase training steps. I can't see any parameter for this. My training is completed upto 960,000 steps. But I want more improved results.
Please help!

**Comment by r9y9** [comment]
Change https://github.com/r9y9/deepvoice3_pytorch/blob/897f31e57eb6ec2f0cafa8dc62968e60f6a96407/hparams.py#L107. But I don't think you can get big improvements if you just train more (I guess your model already reached the limitation of the model)

**Comment by Arafat4341** [comment]
@r9y9 Thanks a lot. 
But the thing is, I get unnatural sound.
I used `deepvoice3_ljspeech.json` as preset for pre-processing, training. 
Later I changed the `"frontend"="jp"` in the deepvoice3_nikls.json file and passed it to `synthesize.py`.
Can you tell me what to do?
