### ISSUE TITLE
Both Sample Colab Notebooks No Longer Work

### ISSUE THREAD

**Issue by windowshopr** [r9y9/deepvoice3_pytorch#229]
![image](https://user-images.githubusercontent.com/40477419/156674081-825f65e0-cfa3-4888-90e0-760aec2c4538.png)

So if we just comment that line out and restart/run all, we then get:

![image](https://user-images.githubusercontent.com/40477419/156674209-f5e53ded-f790-4dd5-8d53-9f8d1b0cfb51.png)

...So we run `!pip install --upgrade hparams`, then restart and run all again, we get:

![image](https://user-images.githubusercontent.com/40477419/156674344-f03af40a-f61c-4f38-87de-7f9ce5b4db66.png)

...and on the single speaker notebook, we get another similar error on this line:

![image](https://user-images.githubusercontent.com/40477419/156674414-3af71c91-d12d-4215-ac0b-8106ad5e5f60.png)

What to do next? Might be time to update those sample notebooks. Thanks!

**Comment by Najib-Haq** [comment]
Single speaker notebook works for me if you change directory to the one where the github repo is cloned (Just change `os.chdir(join(expanduser("~"), name))` to `os.chdir(join('/content/', name))` for colab) and if you remain in the master branch (comment out `!git checkout 7a10ac6763eda92595e257543494b6a95f64229b --quiet.`)

Multi speaker works with similar changes + change `! pip install -q -e '.[train]'` to `! pip install -q -e '.[bin]'`

**Comment by windowshopr** [comment]
Worked! Thanks for the direction!
