### ISSUE TITLE
Phonemes

### ISSUE THREAD

**Issue by B1gM** [r9y9/deepvoice3_pytorch#25]
Hi there,

I was wondering if you were ever considering making adjustments for `JOINT REPRESENTATION OF CHARACTERS AND PHONEMES' as the deepvoice3 paper, part 3.2 mentions.
![33697180-9df6c988-db40-11e7-97c9-03689ca557a8](https://user-images.githubusercontent.com/35441011/34925858-26a2ebda-fa00-11e7-9196-d80e8b043c03.png)

Thanks in advance,

B1gM

**Comment by r9y9** [comment]
This is already implemented. See https://github.com/r9y9/deepvoice3_pytorch/blob/f29c59474bc50d470ffd08d49fe2c8e2b2610dca/hparams.py#L14-L20
