### ISSUE TITLE
"ImportError: dlopen: cannot load any more object with static TLS" in python3.5 synthesis.py ........

### ISSUE THREAD

**Issue by lightsailpro** [r9y9/deepvoice3_pytorch#28]
I got fatal error when testing  synthesis.py. Could you help?

python3.5 synthesis.py --hparams="builder=deepvoice3,preset=deepvoice3_ljspeech" /home/ml/deepvoice3_pytorch/models/20171213_deepvoice3_checkpoint_step000210000.pth ./text_list.txt ./output/

python3.5 synthesis.py --hparams="uilder=nyanko,preset=nyanko_ljspeech" "/home/ml/deepvoice3_pytorch/models/20171129_nyanko_checkpoint_step000585000.pth" "/home/ml/deepvoice3_pytorch/text_list.txt" "/home/ml/deepvoice3_pytorch/output"
Command line args:
 {'--checkpoint-postnet': None,
 '--checkpoint-seq2seq': None,
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': 'uilder=nyanko,preset=nyanko_ljspeech',
 '--max-decoder-steps': '500',
 '--output-html': False,
 '--replace_pronunciation_prob': '0.0',
 '--speaker_id': None,
 '<checkpoint>': '/home/ml/deepvoice3_pytorch/models/20171129_nyanko_checkpoint_step000585000.pth',
 '<dst_dir>': '/home/ml/deepvoice3_pytorch/output',
 '<text_list_file>': '/home/ml/deepvoice3_pytorch/text_list.txt'}
Traceback (most recent call last):
  File "synthesis.py", line 98, in <module>
    hparams.parse(args["--hparams"])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/training/python/training/hparam.py", line 472, in parse
    values_map = parse_values(values, type_map)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/training/python/training/hparam.py", line 206, in parse_values
    raise ValueError('Unknown hyperparameter type for %s' % name)
ValueError: Unknown hyperparameter type for uilder
ml@tesla1a:~/deepvoice3_pytorch$ python3.5 synthesis.py --hparams="uilder=nyanko,preset=nyanko_ljspeech" "/home/ml/deepvoice3_pytorch/models/20171129_nyanko_checkpoint_step000585000.pth" "/home/ml/deepvoice3_pytorch/text_list.txt" "/home/ml/deepvoice3_pytorch/output"
Traceback (most recent call last):
  File "synthesis.py", line 26, in <module>
    import torch
  File "/usr/local/lib/python3.5/dist-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS

**Comment by lightsailpro** [comment]
Moved import torch to the top, which seems resolved the issue.
from docopt import docopt
import torch

**Comment by r9y9** [comment]
Ref: https://github.com/pytorch/pytorch/issues/2083
