### ISSUE TITLE
synthesis.py  - optimize for deployment - custom GPU kernels

### ISSUE THREAD

**Issue by lightsailpro** [r9y9/deepvoice3_pytorch#30]
Does synthesis.py implement the algorithm mentioned in "appendix B - OPTIMIZING DEEP VOICE 3 FOR DEPLOYMENT" of the original paper?
https://arxiv.org/abs/1710.07654

**Comment by r9y9** [comment]
No.

**Comment by lightsailpro** [comment]
Could you add this as a new feature? Right now, it takes 3.8 sec to generate a 9-second wave file with a K40C GPU. 

0 : A 15-year-old student opened fire Tuesday at a high school in rural Kentucky, killing two people and wounding a dozen more, authorities said.
 (142 chars, 26 words)
Response Time: 3.778097
Finished! Check out ./output for generated audio samples.

**Comment by r9y9** [comment]
I am not planning to do that. Happy to accept a PR.

**Comment by imdatsolak** [comment]
@lightsailpro, from what I understand from that paper is that they have written their own GPU-Kernels to do that. Writing an own kernel is not an easy task, actually it is quite difficult, so I understand why @r9y9 does not want to do it...
BTW: it took you 3.8 secs to generate 9sec wave on K40C? What was the sample_rate? Can you upload the audio somewhere to listen to the quality?
I'm using GeForce 1080 Ti (which should be significantly faster and is also significantly cheaper). I'll post results once I have a enough training-epochs...
BTW, @r9y9, again, great work! 👍

**Comment by lightsailpro** [comment]
@imdatsolak, I used the pre-trained Librispeech model. The generated wave is ok, but not very clear. Not sure how to attach a file here.

**Comment by imdatsolak** [comment]
@lightsailpro, just drag-and-drop into the comment field :)
