### ISSUE TITLE
RuntimeError: invalid argument 2: sizes do not match

### ISSUE THREAD

**Issue by nfrik** [r9y9/deepvoice3_pytorch#31]
I downloaded pretrained models and upon running any of them I receive the following error:

My pytorch version is: 0.3.0.post4

RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:101

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synthesis.py", line 125, in <module>
    model.load_state_dict(checkpoint["state_dict"])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 487, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named seq2seq.encoder.embed_tokens.weight, whose dimensions in the model are torch.Size([149, 128]) and whose dimensions in the checkpoint are torch.Size([149, 256]).

**Comment by r9y9** [comment]
Please make sure that you are on the specific git commit noted in the table https://github.com/r9y9/deepvoice3_pytorch#pretrained-models.

**Comment by nfrik** [comment]
Ok thank you!

**Comment by nfrik** [comment]
Unfortunately the problem still persists. I replaced master branch installation with 0421749 commit and still receive the same error.

**Comment by r9y9** [comment]
Could you provide what command and model you are using? I want to reproduce it locally.

**Comment by nfrik** [comment]
From 0421749 commit I run the following script:
python3 synthesis.py ./models/20171222_deepvoice3_vctk108_checkpoint_step000300000 ./models/text_list.txt ./models/

Here is the complete output:

Command line args:
 {'--checkpoint-postnet': None,
 '--checkpoint-seq2seq': None,
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': '',
 '--max-decoder-steps': '500',
 '--output-html': False,
 '--replace_pronunciation_prob': '0.0',
 '--speaker_id': None,
 '<checkpoint>': './models/20171222_deepvoice3_vctk108_checkpoint_step000300000',
 '<dst_dir>': './models/',
 '<text_list_file>': './models/text_list.txt'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 482, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:101

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synthesis.py", line 125, in <module>
    model.load_state_dict(checkpoint["state_dict"])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 487, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named seq2seq.encoder.embed_tokens.weight, whose dimensions in the model are torch.Size([149, 128]) and whose dimensions in the checkpoint are torch.Size([149, 256]).

**Comment by r9y9** [comment]
Okay, the problem is that you didn't specify proper hyper parameters. Try adding the additional command line args: `--hparams="builder=deepvoice3_vctk,preset=deepvoice3_vctk"`. Also, you have to specify speaker_id as well for multi-speaker model. Try adding `--speaker_id=0`.

**Comment by nfrik** [comment]
Thanks for the hparams, totally missed that. I followed your recommendations, except, I set builder to deepvoice3_multispeaker and I was able to produce wav files.

**Comment by mrgloom** [comment]
`python synthesis.py --hparams="builder=deepvoice3_vctk,preset=deepvoice3_vctk" ./20171222_deepvoice3_vctk108_checkpoint_step000300000.pth ./sentences.txt ./temp`

```
Command line args:
 {'--checkpoint-postnet': None,
 '--checkpoint-seq2seq': None,
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': 'builder=deepvoice3_vctk,preset=deepvoice3_vctk',
 '--max-decoder-steps': '500',
 '--output-html': False,
 '--replace_pronunciation_prob': '0.0',
 '--speaker_id': None,
 '<checkpoint>': './20171222_deepvoice3_vctk108_checkpoint_step000300000.pth',
 '<dst_dir>': './temp',
 '<text_list_file>': './sentences.txt'}
Override hyper parameters with preset "deepvoice3_vctk": {
    "n_speakers": 108,
    "speaker_embed_dim": 16,
    "downsample_step": 4,
    "outputs_per_step": 1,
    "embedding_weight_std": 0.1,
    "speaker_embedding_weight_std": 0.05,
    "dropout": 0.050000000000000044,
    "kernel_size": 3,
    "text_embed_dim": 256,
    "encoder_channels": 512,
    "decoder_channels": 256,
    "converter_channels": 256,
    "use_guided_attention": true,
    "guided_attention_sigma": 0.4,
    "binary_divergence_weight": 0.1,
    "use_decoder_state_for_postnet_input": true,
    "max_positions": 1024,
    "query_position_rate": 2.0,
    "key_position_rate": 7.6,
    "key_projection": true,
    "value_projection": true,
    "clip_thresh": 0.1,
    "initial_learning_rate": 0.0005
}
Traceback (most recent call last):
  File "synthesis.py", line 115, in <module>
    model = build_model()
  File "/Users/my_user/external_projects/text-to-speech/deepvoice3_pytorch-multi-speaker/train.py", line 766, in build_model
    model = getattr(builder, hparams.builder)(
AttributeError: module 'deepvoice3_pytorch.builder' has no attribute 'deepvoice3_vctk'
```

**Comment by mennatallah644** [comment]
@r9y9 
i put the same command but i got this error
![with id](https://user-images.githubusercontent.com/32370077/59122412-fdd27180-895a-11e9-8845-64c43120e078.PNG)
