### ISSUE TITLE
Please correct hyperparams

### ISSUE THREAD

**Issue by sjfischr** [r9y9/deepvoice3_pytorch#35]
Since the synthesis script has been altered to accept a builder param called deepvoice3_multispeaker instead of deepvoice3_vctk, please change the table in the pretrained models section of the README to reflect the new hyperparams for vctk. It will eliminate confusion by people using this platform.

Reference Issue #14 

The table entry should read:

> --hparams="builder=deepvoice3_multispeaker,preset=deepvoice3_vctk"

**Comment by r9y9** [comment]
Sorry about that. It seems like you already have a fix. Could you make a PR?

**Comment by sjfischr** [comment]
Done. PR #36
