### ISSUE TITLE
AttributeError: module 'torch.nn.utils' has no attribute 'weight_norm'

### ISSUE THREAD

**Issue by tmulc18** [r9y9/deepvoice3_pytorch#39]
I created a new environment for this project and made it to through the preprocessing for LJ dataset, and now I'm stuck at the training portion.  I get this error

```
Traceback (most recent call last):
  File "train.py", line 906, in <module>
    model = build_model()
  File "train.py", line 799, in build_model
    value_projection=hparams.value_projection,
  File "/mnt/deepvoice3_pytorch/deepvoice3_pytorch/builder.py", line 46, in deepvoice3
    (h, k, 1), (h, k, 3)],
  File "/mnt/deepvoice3_pytorch/deepvoice3_pytorch/deepvoice3.py", line 54, in __init__
    dilation=1, std_mul=std_mul))
  File "/mnt/deepvoice3_pytorch/deepvoice3_pytorch/modules.py", line 104, in Conv1d
    return nn.utils.weight_norm(m)
AttributeError: module 'torch.nn.utils' has no attribute 'weight_norm'
```
when running `python train.py --data-root=./data/ljspeech/ --hparams="builder=deepvoice3,preset=deepvoice3_ljspeech"`

I installed pytorch with `conda install pytorch torchvision cuda90 -c pytorch`.  Any help would be appreciated.

**Comment by imdatsolak** [comment]
Are you using python 3.x?

**Comment by tmulc18** [comment]
Yes. `Python 3.5.4 `.

**Comment by r9y9** [comment]
To isolate problem, can you execute the following command?

```
python -c "import torch; print(torch.__version__), print(torch.nn.utils.weight_norm)"                                                                                                          
```

For reference, I got:

```
 0.3.0b0+aae0ce4
<function weight_norm at 0x7f7e369ddd90>
```

**Comment by alligator19** [comment]
I cannot run this command. also, I have the same issue. 
can you comment what problem could be?
I am using python 3.6

> To isolate problem, can you execute the following command?
> 
> ```
> python -c "import torch; print(torch.__version__), print(torch.nn.utils.weight_norm)"                                                                                                          
> ```
> For reference, I got:
> 
> ```
>  0.3.0b0+aae0ce4
> <function weight_norm at 0x7f7e369ddd90>
> ```

**Comment by G-Wang** [comment]
Your pytorch version is too old, 0.3 only. Update to latest 1.0 version

**Comment by alligator19** [comment]
Requirement already satisfied: torch==1.0.1.post2 from https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl in ./anaconda3/envs/py36/lib/python3.6/site-packages (1.0.1.post2)

**Comment by G-Wang** [comment]
I'm not sure where your pytorch installation went wrong, you may have to clear all old pytorch version and re-install pytorch again with Conda.

Your printout from previous thread say python is detecting Pytorch version 0.3.0, which is very old. i.e
`0.3.0b0+aae0ce4`

This doesn't have anything to do with Deepvoice 3.

**Comment by r9y9** [comment]
Please check that your pytorch installation is successfully done.  See also https://discuss.pytorch.org/.
