### ISSUE TITLE
Request a demo_server.py

### ISSUE THREAD

**Issue by lightsailpro** [r9y9/deepvoice3_pytorch#42]
For easy test, is there any way to add a demo_server similar to the one (demo_server.py) here https://github.com/keithito/tacotron ?

Great works! Thanks a lot.

**Comment by r9y9** [comment]
I think Jupyter notebook is enough and easy to implement, like I did in http://nbviewer.jupyter.org/github/r9y9/tacotron_pytorch/blob/master/notebooks/Test%20Tacotron.ipynb.

**Comment by r9y9** [comment]
https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/DeepVoice3_multi_speaker_TTS_en_demo.ipynb

This is not a *demo server* but I believe this is easier to try. You don't even need to setup machines locally.
