### ISSUE TITLE
KeyError: 'unexpected key "seq2seq.decoder.attention.in_projection.bias" in state_dict'

### ISSUE THREAD

**Issue by nsmetanin** [r9y9/deepvoice3_pytorch#45]
Hi, thanks for the fantastic DeepVoice3 implementation!

When trying to train Nyanko model starting from your pre-trained checkpoint using the following args:

```
--hparams="builder=nyanko,preset=nyanko_ljspeech" 
--checkpoint=checkpoints.pretrained/20171129_nyanko_checkpoint_step000585000.pth
```

I'm getting the error:
```
Load checkpoint from: checkpoints.pretrained/20171129_nyanko_checkpoint_step000585000.pth
Traceback (most recent call last):
  File "train.py", line 936, in <module>
    load_checkpoint(checkpoint_path, model, optimizer, reset_optimizer)
  File "train.py", line 820, in load_checkpoint
    model.load_state_dict(checkpoint["state_dict"])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 490, in load_state_dict
    .format(name))
KeyError: 'unexpected key "seq2seq.decoder.attention.in_projection.bias" in state_dict'
```

Looks like `in_projection` is missing from `AttentionLayer` implementation in [deepvoice3_pytorch/deepvoice3.py](deepvoice3_pytorch/deepvoice3.py) but still in the Nyanko pre-trained model https://github.com/r9y9/deepvoice3_pytorch#pretrained-models

**Comment by r9y9** [comment]
Consider using —restore-parts option instead. Invalid size or unknown name of parameters will be ignored and training should start normally.

**Comment by nsmetanin** [comment]
@r9y9 Yes, thanks, already did that! I'm just wondering if there's some model/code version mismatch? Does it still make sense to pre-initialize my model with this weights? I mean that attention layer probably had to be retrained completely.

**Comment by r9y9** [comment]
Yes,  I think you are right. Attention layer needs to be traiThe mismatch exists because I changed the attention layer after I trained the Nyanko model a while ago.

**Comment by r9y9** [comment]
Sorry, that was unintentional. I agree attention layer needs to be trained completely. You may also try —load-embedding option, which  I think makes more sense.

**Comment by nsmetanin** [comment]
@r9y9 Ok, great, I'll retrain it from scratch up to 585k iterations on LJSpeech and publish there (~2 days of training left)

**Comment by nsmetanin** [comment]
Here it is — https://www.dropbox.com/s/tccmm2tmjq49r1f/02032018_nyanko_ljspeech_checkpoint_step000700000.pth?dl=0 Nyanko model trained on an actual source code for 700k iterations. Sounds very good, but sometimes (very occasionally) it doesn't stop at the end and continues with producing a few seconds of noise.

**Comment by seatonullberg** [comment]
I'm getting this same error when I try to use synthesis.py on the 585K pre-trained model you provided. Is there a work around or modification I can do without training and using --restore-parts?

**Comment by nsmetanin** [comment]
@seatonullberg Please try my model (on 700k steps) provided above, it was trained on more recent version of code.

**Comment by seatonullberg** [comment]
That leaves me this error.
KeyError: 'unexpected key "seq2seq.encoder.convnet.0.bias" in state_dict'

**Comment by shwetagargade216** [comment]
Hello @nsmetanin  Could you please share your model what was trained for 700k

**Comment by mennatallah644** [comment]
@r9y9 
i have the same error when synthesizing through my adapted model how can i use --load-embedding while synthesizing ?
![error](https://user-images.githubusercontent.com/32370077/58984694-f041ae00-87d9-11e9-9b57-92b341338f2c.PNG)
 Thanks
