### ISSUE TITLE
error on training

### ISSUE THREAD

**Issue by chesterkuo** [r9y9/deepvoice3_pytorch#49]
I got following error when i try to train model. Did this due to i have some speech with very long (such as 30 seconds) and bring issue ?

======
Los event path: ./log/aclclp
^M0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 950, in <module>
    train_seq2seq=train_seq2seq, train_postnet=train_postnet)
  File "train.py", line 685, in train
    priority_w=hparams.priority_freq_weight)
  File "train.py", line 510, in spec_loss
    l1_loss = w * masked_l1(y_hat, y, mask=mask) + (1 - w) * l1(y_hat, y)
  File "/home/chester/hdd22t/virtualenv/deepvoice3-pytorch-r9y9/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 280, in forward
    loss = self.criterion(input * mask_, target * mask_)
RuntimeError: The size of tensor a (1025) must match the size of tensor b (513) at non-singleton dimension 2

**Comment by r9y9** [comment]
Can you provide what command you use? And also please provide full log output (stdout/stderr) to help us fix this.

**Comment by chesterkuo** [comment]
Cmd:
python3 train.py --data-root=./data/aclclp --checkpoint-dir=./ckpt/aclclp \
    --hparams="builder=deepvoice3,preset=deepvoice3_ljspeech" \
    --log-event-path=./log/aclclp

Log:

Command line args:
 {'--checkpoint': None,
 '--checkpoint-dir': './ckpt/aclclp',
 '--checkpoint-postnet': None,
 '--checkpoint-seq2seq': None,
 '--data-root': './data/aclclp',
 '--help': False,
 '--hparams': 'builder=deepvoice3,preset=deepvoice3_ljspeech',
 '--load-embedding': None,
 '--log-event-path': './log/aclclp',
 '--reset-optimizer': False,
 '--restore-parts': None,
 '--speaker-id': None,
 '--train-postnet-only': False,
 '--train-seq2seq-only': False}
Training whole model
Training seq2seq model
Hyperparameters:
  adam_beta1: 0.5
  adam_beta2: 0.9
  adam_eps: 1e-06
  allow_clipping_in_normalization: False
  batch_size: 8
  binary_divergence_weight: 0.1
  builder: deepvoice3
  checkpoint_interval: 2000
  clip_thresh: 0.1
  converter_channels: 256
  decoder_channels: 256
  downsample_step: 4
  dropout: 0.050000000000000044
  embedding_weight_std: 0.1
  encoder_channels: 256
  eval_interval: 10000
  fft_size: 1024
  fmax: 7600
  fmin: 125
  force_monotonic_attention: True
  freeze_embedding: False
  frontend: en
  guided_attention_sigma: 0.2
  hop_size: 256
  initial_learning_rate: 0.0005
  kernel_size: 3
  key_position_rate: 1.385
  key_projection: False
  lr_schedule: noam_learning_rate_decay
  lr_schedule_kwargs: {}
  masked_loss_weight: 0.5
  max_positions: 1024
  min_level_db: -100
  n_speakers: 1
  name: deepvoice3
 nepochs: 2000
  num_mels: 80
  num_workers: 2
  outputs_per_step: 1
  padding_idx: 0
  pin_memory: True
  power: 1.4
  preemphasis: 0.97
  preset: deepvoice3_ljspeech
 presets: {'nyanko_ljspeech': {'key_projection': False, 'encoder_channels': 256, 'value_projection': False, 'downsample_step': 4, 'max_positions': 512, 'decoder_channels': 256, 'binary_divergence_weight': 0.1, 'text_embed_dim': 128, 'outputs_per_step': 1, 'n_speakers': 1, 'use_guided_attention': True, 'query_position_rate': 1.0, 'dropout': 0.050000000000000044, 'converter_channels': 256, 'key_position_rate': 1.385, 'guided_attention_sigma': 0.2, 'clip_thresh': 0.1, 'embedding_weight_std': 0.01, 'use_decoder_state_for_postnet_input': True, 'kernel_size': 3, 'initial_learning_rate': 0.0005}, 'deepvoice3_ljspeech': {'key_projection': True, 'encoder_channels': 512, 'value_projection': True, 'downsample_step': 4, 'max_positions': 1024, 'decoder_channels': 256, 'binary_divergence_weight': 0.1, 'text_embed_dim': 256, 'outputs_per_step': 1, 'n_speakers': 1, 'use_guided_attention': True, 'query_position_rate': 1.0, 'dropout': 0.050000000000000044, 'converter_channels': 256, 'key_position_rate': 1.385, 'guided_attention_sigma': 0.2, 'clip_thresh': 0.1, 'embedding_weight_std': 0.1, 'use_decoder_state_for_postnet_input': True, 'kernel_size': 3, 'initial_learning_rate': 0.0005}, 'deepvoice3_niklm': {'dropout': 0.050000000000000044, 'downsample_step': 4, 'decoder_channels': 256, 'text_embed_dim': 256, 'binary_divergence_weight': 0.1, 'use_guided_attention': True, 'key_position_rate': 7.6, 'guided_attention_sigma': 0.4, 'clip_thresh': 0.1, 'embedding_weight_std': 0.1, 'speaker_embedding_weight_std': 0.05, 'encoder_channels': 512, 'max_positions': 1200, 'outputs_per_step': 1, 'batch_size': 8, 'n_speakers': 118, 'query_position_rate': 2.0, 'key_projection': True, 'value_projection': True, 'speaker_embed_dim': 16, 'converter_channels': 256, 'use_decoder_state_for_postnet_input': True, 'kernel_size': 3, 'initial_learning_rate': 0.0005}, 'deepvoice3_nikls': {'dropout': 0.050000000000000044, 'downsample_step': 4, 'decoder_channels': 256, 'text_embed_dim': 256, 'binary_divergence_weight': 0.1, 'use_guided_attention': True, 'key_position_rate': 7.6, 'guided_attention_sigma': 0.4, 'clip_thresh': 0.1, 'embedding_weight_std': 0.1, 'speaker_embedding_weight_std': 0.05, 'encoder_channels': 512, 'max_positions': 512, 'outputs_per_step': 1, 'batch_size': 8, 'n_speakers': 1, 'query_position_rate': 2.0, 'key_projection': True, 'value_projection': True, 'speaker_embed_dim': 16, 'converter_channels': 256, 'use_decoder_state_for_postnet_input': True, 'kernel_size': 3, 'initial_learning_rate': 0.0005}, 'deepvoice3_vctk': {'dropout': 0.050000000000000044, 'downsample_step': 4, 'decoder_channels': 256, 'text_embed_dim': 256, 'binary_divergence_weight': 0.1, 'use_guided_attention': True, 'key_position_rate': 7.6, 'guided_attention_sigma': 0.4, 'clip_thresh': 0.1, 'embedding_weight_std': 0.1, 'speaker_embedding_weight_std': 0.05, 'encoder_channels': 512, 'max_positions': 1024, 'outputs_per_step': 1, 'n_speakers': 108, 'query_position_rate': 2.0, 'key_projection': True, 'value_projection': True, 'speaker_embed_dim': 16, 'converter_channels': 256, 'use_decoder_state_for_postnet_input': True, 'kernel_size': 3, 'initial_learning_rate': 0.0005}}
  priority_freq: 3000
  priority_freq_weight: 0.0
  query_position_rate: 1.0
  ref_level_db: 20
 replace_pronunciation_prob: 0.5
  rescaling: False
  rescaling_max: 0.999
  sample_rate: 22050
  save_optimizer_state: True
  speaker_embed_dim: 16
  speaker_embedding_weight_std: 0.01
  text_embed_dim: 128
  trainable_positional_encodings: False
  use_decoder_state_for_postnet_input: True
  use_guided_attention: True
  use_memory_mask: True
  value_projection: False
  weight_decay: 0.0
  window_ahead: 3
  window_backward: 1
Override hyper parameters with preset "deepvoice3_ljspeech": {
    "key_projection": true,
    "encoder_channels": 512,
    "value_projection": true,
    "downsample_step": 4,
    "max_positions": 1024,
    "decoder_channels": 256,
    "binary_divergence_weight": 0.1,
    "text_embed_dim": 256,
    "outputs_per_step": 1,
    "n_speakers": 1,
    "use_guided_attention": true,
    "query_position_rate": 1.0,
    "dropout": 0.050000000000000044,
    "converter_channels": 256,
    "key_position_rate": 1.385,
    "guided_attention_sigma": 0.2,
"clip_thresh": 0.1,
    "embedding_weight_std": 0.1,
    "use_decoder_state_for_postnet_input": true,
    "kernel_size": 3,
    "initial_learning_rate": 0.0005
}
Los event path: ./log/aclclp
^M0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 950, in <module>
    train_seq2seq=train_seq2seq, train_postnet=train_postnet)
  File "train.py", line 685, in train
    priority_w=hparams.priority_freq_weight)
  File "train.py", line 510, in spec_loss
    l1_loss = w * masked_l1(y_hat, y, mask=mask) + (1 - w) * l1(y_hat, y)
  File "/home/chester/hdd22t/virtualenv/deepvoice3-pytorch-r9y9/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 280, in forward
    loss = self.criterion(input * mask_, target * mask_)
RuntimeError: The size of tensor a (1025) must match the size of tensor b (513) at non-singleton dimension 2

**Comment by chesterkuo** [comment]
@r9y9 , this is full log (redirect with nohup)

**Comment by RaghothamRao** [comment]
@chesterkuo even i get this error while trying to train the LJspeech model for speaker adaptation. I have pytorchversion 1.1, torchvision 0.3.0, cuda9 & Tensorflow 1.10. Just curious to know the fix as i don't see any mention about fix here.
