### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by ManivannanMurugavel** [r9y9/deepvoice3_pytorch#5]
When i ran the train.py
(python3 train.py --data-root=./datapath/ljspeech/ --hparams="batch_size=10")

This error is came:
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f1b5f86a710>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 3359, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop

**Comment by r9y9** [comment]
What line of train.py causes the error?

**Comment by ManivannanMurugavel** [comment]
it did not show what the line.
only show the error is
Exception ignored in: <bound method Image.del of <tkinter.PhotoImage object at 0x7f1b5f86a710>>
Traceback (most recent call last):
File "/usr/lib/python3.5/tkinter/init.py", line 3359, in del
self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop

**Comment by r9y9** [comment]
Well, after some googling, It seems there's a problem in your GUI backend for matplotlib. Does the following code work for you?

```py
import matplotlib
import matplotlib.pyplot as plt 
plt.plot([1,2,3])
```

and

```py
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt 
plt.plot([1,2,3])
```

**Comment by ManivannanMurugavel** [comment]
i tried this way but the same error is came.
i also googling.
please help me.
(plese send your mail id to manivannanmca2012@gmail.com)

**Comment by r9y9** [comment]
So the issue is not related to deepvoice3_pytorch. Please ask a question or file an issue to matplotlib community. I cannot reproduce.

**Comment by ManivannanMurugavel** [comment]
I have solved this error.
Thank you

**Comment by toannhu** [comment]
@ManivannanMurugavel I have the same problem as you? Could you show me the way to fix it? Really appreciate!

**Comment by ManivannanMurugavel** [comment]
@toannhu Please remove matplotlib for loss and accuracy graph.
Just see the what training acc and loss in terminal.
**Solution:**
Please command the all save_alignment() def inside train.py.

**Comment by thakur101** [comment]
@ManivannanMurugavel I have encountered the same error 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 772, in after_cancel
    data = self.tk.call('after', 'info', id)
RuntimeError: main thread is not in main loop
can you please help me with this ?
