### ISSUE TITLE
Persistent MemoryError while training on VCTK

### ISSUE THREAD

**Issue by engiecat** [r9y9/deepvoice3_pytorch#50]
Hello. I am currently trying to train VCTK model on deepvoice 3 multispeaker model.
While it seems that it works okay, sometimes the training crashes with the following error.

```
2734it [13:58,  3.26it/s]Traceback (most recent call last):
  File "train.py", line 957, in <module>
    train_seq2seq=train_seq2seq, train_postnet=train_postnet)
  File "train.py", line 585, in train
    in tqdm(enumerate(data_loader)):
  File "H:\envs\pytorch\lib\site-packages\tqdm\_tqdm.py", line 959, in __iter__
    for obj in iterable:
  File "H:\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "H:\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
MemoryError: Traceback (most recent call last):
  File "H:\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "H:\Tensorflow_Study\git\deepvoice3_pytorch\train.py", line 329, in collate_fn
    dtype=np.float32)
MemoryError
```

Forcing garbage collection sporadically(**using gc.collect()**) doesn't help the issue.
Currently, I have 16 GB of RAM with 48 GB of virtual memory available on my SSD (just in case).
(Using Windows 10 with PyTorch 0.3.1 (with CUDA 8.0, GTX1060 6GB))

Also, I do observe that in Resource Monitor, the memory usage in **Commit(KB)** and **Working Set(KB)** is significantly different, as shown below. (Sorry for the non-english)
![image](https://user-images.githubusercontent.com/13521426/36941100-7ebe96fa-1f96-11e8-9e1d-faffcb4508af.png)

Thank you for creating such wonderful implementation!
:)

**Comment by r9y9** [comment]
Thank you for the report. I have never seen MemoryError on Linux, so I'm guessing this is a windows-specific issue...  If `gc.collect()` doesn't help, this is possibly a pytorch (C++-side) issue.

**Comment by r9y9** [comment]
Maybe worth trying `num_workers=1` for DataLoader? https://github.com/r9y9/deepvoice3_pytorch/blob/5dc44267e17cd25b83ad8509f0495984272dfbe0/hparams.py#L82-L84

**Comment by engiecat** [comment]
@r9y9 It didn't crash for 12 hours. (compared to ~2.5 hrs previously) 
Thank you for your assistance!!!

**Comment by engiecat** [comment]
Fixed for now!
