### ISSUE TITLE
Getting error when num_workers > 0

### ISSUE THREAD

**Issue by amilamad** [r9y9/deepvoice3_pytorch#53]
Hi,
I have tried to train the lj speech model with latest mater and it gives me error like this, with 

num_workers = 2
![image](https://user-images.githubusercontent.com/8535277/36988587-3df9ac10-20c5-11e8-9d9a-bbe2c068835e.png)
It looks like _frontend for worker processes didn`t got assigned. I tried injecting _frontend object to the TextDataSource.  But It failed.   Is there a fix for this ?

When I set the num_workers = 0 , it is training ok.
After quick google search it tells me that when num_workers = 0 it will do all the work in main thread.
My question is, will it slow down my training process significantly ?

**Comment by r9y9** [comment]
Seems dup of #37.

**Comment by r9y9** [comment]
This is not really tested on Windows, so I'd recommend Linux instead if possible. 

`_frontend` should be `deepvoice3_pytorch.frontend.en` for English datasets, not TextDataSource. I'm not sure wha's happening in the num_workers=0 case.

**Comment by amilamad** [comment]
Oh sorry again for duplicate issue.
`_frontend `is initialized correctly with the `deepvoice3_pytorch.frontend.en` in the main python thread. But when it is accessed by worker threads `_frontend ` is` None` .I think this issue is due to the nature of the python worker threads on windows.
Ill place a issue on the [https://github.com/peterjc123/pytorch-scripts](url) 

Now my training is running ok with `num_workers=0`. Can I know will it significantly slow down compared to *num_workers=2* case ?

**Comment by engiecat** [comment]
@amilamad 
I am currently working with VCTK set on Win 10 and num_workers=1 does work well. (About 10% loss of performance is observed.)
![image](https://user-images.githubusercontent.com/13521426/37134278-2dae5a5a-22db-11e8-95c3-d7bbbf57829a.png)
THAllocator error does occur(approx. once per day for me) though, but according to https://github.com/pytorch/pytorch/issues/4239, it can be alleviated.
