### ISSUE TITLE
Speed up training.

### ISSUE THREAD

**Issue by edwinlimlx** [r9y9/deepvoice3_pytorch#55]
Hi r9y9, 
Thanks for the amazing library here. I'm only beginning to learn ML, and love what this can do! Ultimately trying to create what lyrebird.ai has been doing. Managed to finally setup it all up and started training single speaker with the ljspeech. 

However i'm experiencing same training speed of ~3s/it between my dekstop specs below and my MBP (2.5Ghz, i8, 4 Cores). is there a way I can speed things up? I know I don't have the ideal AI training hardware specs, but kinda looking forward to the results. 

_*Both setup has all CPU cores running at 100%_

OS: Ubuntu 16.04.4
CPU: i7-7820X (8 CORE)
GPU: 2x 1080 Ti

**Comment by amilamad** [comment]
Try increasing num_workers in preset json

**Comment by edwinlimlx** [comment]
Can I ask if it's utilizing the CPU only? changing from default 2 to 8 did but wasn't significant.

**Comment by amilamad** [comment]
@edwinlimlx  according to [https://github.com/r9y9/deepvoice3_pytorch/issues/15](url) it only supports GPU only.

**Comment by amilamad** [comment]
@edwinlimlx 
I have done some tests,
[Training_stat.xlsx](https://github.com/r9y9/deepvoice3_pytorch/files/1799188/Training_stat.xlsx)
Looks like `num_workers = 1` have the nearly same performance as  `num_workers = 4` 

I think it does not scale well with no of workers.
@r9y9  Please correct me If i am wrong

**Comment by edwinlimlx** [comment]
@amilamad thanks for answering my question! Looking forward to more update and enhancement to this!

_*Don't wish to add more issues to the repo._

**Comment by mrgloom** [comment]
`816it [10:07,  1.04it/s] `on `GTX 1080 Ti` running `time python train.py --preset=presets/deepvoice3_ljspeech.json --data-root=/tts-datasets/LJSpeech-1.1-prepared`
GPU utilization is 100%.
