### ISSUE TITLE
Crowdsourcing a high-quality, open-source TTS dataset

### ISSUE THREAD

**Issue by fatchord** [r9y9/deepvoice3_pytorch#59]
Hi r9y9, first I just want to say that your repos are great and I have personally learned a lot from them. So a big thanks to you. 

So I too have been trying to replicate the results of the big TTS papers. However the main thing that is frustrating me is the lack of a high quality TTS dataset (although 50 gpus would help too!). 

I just wanted to throw this idea out there - what if random people on the internet interested in TTS/ML collaborated to create a good dataset? If enough people joined in (20+)  the segmentation and labelling work should only be a couple of hours per person. 

Here is a list of the options that occurred to me (and I by no means consider this list complete):

1 - Find a 20+ hour high-quality, open-source audiobook online. Given how massive the internet is - surely there is a possibility of a hi-fi audiobook that isn't poorly recorded, overly-compressed or too 'performed'. Working together, scouring the internet... who knows - a gem might be out there. 

2 - Podcasts - there's an endless supply of these. But podcasts bring their own unique difficulties - e.g., were different eq/compression/mic/mastering used by the sound engineer across different episodes? Again, with enough searching, a candidate with consistent sound-quality may reveal itself.

3 - Commercial Audiobooks - this would unfortunately render the whole dataset closed-sourced and for personal research only. However I don't see how there would be any problems if all collaborators purchased the audiobook and didn't redistribute the dataset beyond the initial group of collaborators. 

4 - Crowdfunding it - probably the least realistic option. Still though, if enough people were interested, 100 or so, then it might be possible. One studio, one sound engineer, one professional reader and someone to oversee the project for a week or two weeks max? Would $10,000 cover it? $20,000? I'm no expert in studio time and sound-engineering rates etc so I can't say for certain.

So to wrap this up - I just wanted to put this idea out there. I'm very curious what you, or any others reading this, think - even if you feel it's unrealistic. I know buying 50 gpus is unfeasible for most of us - but working together to solve the dataset problem? Personally, I'm optimistic.

**Comment by engiecat** [comment]
Well for me, i used
1. Open sourced dataset(e.g. VCTK, NIKL, LJs)
2. Open source audiobook(check out librivox)

3. Easily available dataset such as
3-1. Presidential speech uploaded by the govt
(Better if she is impeached and imprisoned so she cannot file DMCA!)
3-2. Podcasts!
3-3. TV news segments available online
For those cases You might probably wanna check out
https://github.com/GSByeon/multi-speaker-tacotron-tensorflow?files=1
(The original contributor is https://github.com/carpedm20/multi-speaker-tacotron-tensorflow but he deleted case 3-1 and 3-2)
4. closed sourced audiobook(i made a very rudimentary one myself)

+) for opensourced, free voice recognition check out https://github.com/mozilla/DeepSpeech

**Comment by engiecat** [comment]
Well for me, i used

Open sourced dataset(e.g. VCTK, NIKL, LJs)

Open source audiobook(check out librivox)

Easily available dataset such as
3-1. Presidential speech uploaded by the govt
(Better if impeached and imprisoned so DMCA complaint is improbable!!)
3-2. Podcasts!
3-3. TV news segments available online
For those cases You might probably wanna check out
https://github.com/GSByeon/multi-speaker-tacotron-tensorflow?files=1
(The original contributor is https://github.com/carpedm20/multi-speaker-tacotron-tensorflow but he deleted case 3-1 and 3-2)

closed sourced audiobook(i made a very rudimentary one myself)

+) for opensourced, free voice recognition check out https://github.com/mozilla/DeepSpeech
