### ISSUE TITLE
How to evaluate the quality of synthesized speech？

### ISSUE THREAD

**Issue by zuoxiang95** [r9y9/deepvoice3_pytorch#62]
Hi  r9y9,
    For TTS area, I am a newcomer. Apart from MOS,  do you know what else can be used to evaluate the quality of synthesized speech? Looking forward your kind reply. Thanks~

**Comment by r9y9** [comment]
I'm not so familiar with evaluation metrics for TTS. You can check out scientific papers here: https://research.google.com/pubs/HeigaZen.html.

**Comment by pbaljeka** [comment]
@zuoxiang95  
This might be helpful:
http://tts.speech.cs.cmu.edu/courses/11492/slides/tts_eval.pdf

You could use MCD(Mean Cepstral distortion) as an objective metric..(its a weighted Euclidean distance between true and synthesized acoustic vector).. assumes you have ground truth data.
mcd implementation between two Mceps:
https://github.com/festvox/festvox/blob/master/src/clustergen/track_diff_mcd

MCD implementation between two wavfiles using DTW:
https://github.com/festvox/festvox/blob/master/src/clustergen/get_cd_dtw

Other Implementation:
https://github.com/MattShannon/mcd

Alternatively, you could use SUS (Semantically Unpredictable sentences)  for Understandability judgement asking users to transcribe SUS sentences and measure word error rate.

**Comment by rafaelvalle** [comment]
You could also use word error rate
