### ISSUE TITLE
Error While Running Synthesis.py

### ISSUE THREAD

**Issue by dheeru999** [r9y9/deepvoice3_pytorch#63]
I'am face an issue while running Synthesis.py
Please can anyone suggest me to resolve this issue.

![screenshot from 2018-03-23 18-56-05](https://user-images.githubusercontent.com/31062594/37831596-1b7eb314-2ecc-11e8-9834-044a1c767596.png)

**Comment by r9y9** [comment]
https://github.com/r9y9/deepvoice3_pytorch/blob/708a24174aba42e4af9ebde917a4e996ec60f4ba/.travis.yml#L30
