### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by abhishekkritarth** [r9y9/deepvoice3_pytorch#66]
@r9y9 
Hi I have gone through your code.I need to do transfer learning for this model and add new speakers for the model and Train the model for new speakers.How could I do transfer learning for the model.Kindly reply me back.

Thanks and Regards,
Kritarth.

**Comment by r9y9** [comment]
Go through the README and see speaker adaptation section in https://github.com/r9y9/deepvoice3_pytorch#advanced-usage.
