### ISSUE TITLE
 About input value of audio  preprocessing./入力音声の処理について

### ISSUE THREAD

**Issue by Sumid1** [r9y9/deepvoice3_pytorch#68]
Hi.
I'm interesting to deep voice3 so I think I want to make this model myself.
Now, I read the report of this model but I can't understand input of decoder.
The report say, it's mel-scale log magnitude spectrograms. This mean to MFCC or mel-scale log power spectrograms or other? However I read your code "audio.py" but I can't understand so I also want to know how to make it. 
Sorry unclear my English. Thank you..

こんにちは。
私はdeep voice3に興味を持っていて、自分で実装したいと考えています。
私は、論文を読んだのですがデコーダーに入力する音声がよくわかりませんでした。
論文中にはmel-scale log magnitude spectrogramsとあるのですが、これはメル周波数ケプストラムかメル対数振幅スペクトラムかそれともほかの何かが分かりませんでした。audio.py を読んだのですがよく理解できなかったのでご教授頂ければと思います。
よろしくお願いします。

**Comment by r9y9** [comment]
See https://github.com/r9y9/deepvoice3_pytorch/blob/1223c7825c17655ce017e3ff37649f89abc36211/audio.py#L46-L51.

In short, 

```py
import librosa
x, sr = librosa.load(librosa.util.example_audio_file())
# set power=2 if you want power spectrogram
this_is_what_we_want = np.log(librosa.feature.melspectrogram(y=y, sr=sr, power=1))
```

https://librosa.github.io/librosa/generated/librosa.feature.melspectrogram.html

I'm not sure what you are unclear with. mel-scale log magnitude spectrogram is clear enough to me. It's not MFCC, mel-cepstrum, nor linear-frequency spectrogram.  日本語で言うなら、メル周波数対数振幅スペクトログラム、でしょうか

**Comment by Sumid1** [comment]
Thank,you! I'll write your short program. In the future, when I have questions, I'll listen to you.

実装まで書いてくださりありがとうございます。今後も何かと質問すると思いますがよろしくお願いいたします。
