### ISSUE TITLE
hparams is not updated across threads in windows

### ISSUE THREAD

**Issue by amilamad** [r9y9/deepvoice3_pytorch#69]
Hi,
In `TextDataSource:collect_features(self)` function there is code to get the frontend from the worker thread
`global _frontend`
 `if _frontend is None:`
 `           _frontend = getattr(frontend, hparams.frontend)`

I have created my own frontend and changed the `"frontend": "en"` in my preset json to `"frontend": "sin"` (**sin** is my frontend for **sinhala** language). But only main thread `hparam.frontend ` gives **sin**
as the frontend name.
`TextDataSource:collect_features(self)` function will still gives `hparam.frontend` as **en** (I guess the default value of the  `hparam.frontend`)

As a solution I have passed the `hparam.frontend` to the `TextDataSource` objects and used it on the worker threads `TextDataSource:collect_features(self)` function and it worked correctly. If I did a correct thing I can send a PR.

I am using Windows 10
Thanks

**Comment by r9y9** [comment]
That sounds reasonable to me. Could you create a PR?
