### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by jraulhernandezi** [r9y9/deepvoice3_pytorch#76]
Hi, are interested in having a logo for you project? I could send you some ideas if you like.

**Comment by r9y9** [comment]
I haven't thought about logo but yeah it would be nice to have. I'm happy to your suggestions.

**Comment by jraulhernandezi** [comment]
I´m working on it, the typography should be Pytorch, or Deepvoice 3 Pytorch?

**Comment by r9y9** [comment]
Deep Voice 3 Pytorch sounds good to me.

https://arxiv.org/abs/1710.07654

**Comment by jraulhernandezi** [comment]
What do you think about this one?, I used a wave sound figure inside a form inspired on the PyTorch Logotype.

![image](https://user-images.githubusercontent.com/35578070/39389958-fd87cbf6-4a5b-11e8-9393-f6e48e4cc159.png)

**Comment by r9y9** [comment]
Cool!

**Comment by r9y9** [comment]
Would you mind creating a PR that puts the logo into README and https://github.com/r9y9/deepvoice3_pytorch/blob/master/docs/static/favicon.png?

**Comment by jraulhernandezi** [comment]
Ok, i´m on it!

**Comment by r9y9** [comment]
https://r9y9.github.io/deepvoice3_pytorch/ the project page updated. Thank you very much,  @jraulhernandezi.

**Comment by r9y9** [comment]
I'm closing the issue. Thanks again
