### ISSUE TITLE
accuracy of the model

### ISSUE THREAD

**Issue by vinaykumarbundla** [r9y9/deepvoice3_pytorch#84]
HI,
@r9y9
What is the accuracy for vctk dataset for deep voice 3 model and Will be any change by replacing wavenet with world vocoder.
What is the accuracy for Lj speech dataset for deep voice 3 model.

**Comment by r9y9** [comment]
Dup of #81. I'm sorry but I really don't understand what you mean by accuracy here. Closing as inappropriate issue.
