### ISSUE TITLE
Structure of train.txt?

### ISSUE THREAD

**Issue by yrahul3910** [r9y9/deepvoice3_pytorch#88]
I'm trying to adapt the trained model `20180505..` to a new (single) speaker, whose mp3 recordings are in a folder called recordings, and I used:
```
python3 train.py --data-root=../Recordings --checkpoint-dir=checkpoints_adaptation --preset=presets/deepvoice3_ljspeech.json --log-event-path=log/adaptation --restore-parts=../20180505_deepvoice3_checkpoint_step000640000.pth
```
to try adapting to the data, but it asks for a `train.txt` file. The [VCTK dataset](http://homepages.inf.ed.ac.uk/jyamagis/page3/page58/page58.html) I downloaded does not have one of these. How should I structure my `train.txt` file for it to adapt to the new speaker correctly?

**Comment by yrahul3910** [comment]
Sorry, a RTFM. I created an `alignment.json` for the MP3s, used `ffmpeg -i sentence01.mp3 -acodec pcm_s16le sentence01.wav` (and similar commands) for the files, and used the preprocessing command from the README, which then created the required `train.txt` file.

**Comment by shwetagargade216** [comment]
Could you please let me know structure of data ?

**Comment by shwetagargade216** [comment]
for the speaker adaption which preprocess command should i use ?
