### ISSUE TITLE
What is “incremental inference” supported conv1d ?

### ISSUE THREAD

**Issue by Sumid1** [r9y9/deepvoice3_pytorch#91]
Hello.
I want to learn your conv1d especially “Incremental inference”.
what is it function?
what is difference between  “Incremental inference” conv1d and normal conv1d.
If you used reports or programs created by other people,  I want you to teach them. 
Thank you.

**Comment by r9y9** [comment]
I think the name says what the function is... Also please read the code https://github.com/r9y9/deepvoice3_pytorch/blob/master/deepvoice3_pytorch/conv.py. It's just 60 lines of code.

**Comment by Sumid1** [comment]
Thank you!
I understand your conv1d.
I read "https://qiita.com/r9y9/items/665f84929994c05c6d06" and "https://github.com/facebookresearch/fairseq-py/blob/884e30464b8f6a74bfaea5688b31e2005e0fbef5/fairseq/modules/conv_tbc.py ".

If I correct understanding your  conv1d, that mean is faster conv1d uesed data that has timestep than normal conv1d.

**Comment by r9y9** [comment]
Honestly, I'm not sure if I understand you correctly. Anyway, I believe the name "incremental inference" is clear and the code is simple to read. Unit tests https://github.com/r9y9/deepvoice3_pytorch/blob/271863f1fccfcb21b413600dfeeb6dbe6ba9c3fc/tests/test_conv.py might help you understand the behavior. I'm closing.
