### ISSUE TITLE
Input Japanese data.

### ISSUE THREAD

**Issue by Sumid1** [r9y9/deepvoice3_pytorch#92]
Hello.
I want to implement a network used deepvoice3 you created as reference.
Should I convert words to “Hiragana” or “Katakana” characters if i use japanese?
I need not “romaji” or “phoneme” or anything else.
The report(“deepvoice3”) said, “we also train phoneme-only models and mixed character-and-phoneme models by allowing phoneme input option explicitly.”.
I should also convert English word to the alphabet?
What do you think?

**Comment by r9y9** [comment]
You can find my thoughts for Japanese end-to-end TTS at https://github.com/r9y9/deepvoice3_pytorch/issues/61#issuecomment-373923968.

**Comment by Sumid1** [comment]
I read the issue.
According your idea said the issue, input data is original script and these expressions KATAKANA.
Is original script words that mixed KANJI and HIRAGANA and so on?

**Comment by r9y9** [comment]
I think so.

**Comment by Sumid1** [comment]
Thank you so much! I'll try it!
