### ISSUE TITLE
training stopped at 0 iteration

### ISSUE THREAD

**Issue by Ersho** [r9y9/deepvoice3_pytorch#94]
I have made every preprocessing step required, preprocess.py was also finished successfully,

but when I run the following code

``python train.py --preset=presets/deepvoice3_ljspeech.json --data-root=./data/ljspeech/
``

everything seems to run correctly but it just stops the training and nothing happens. Even 'finished' is not printed and I get no error.  Can you help?

![capture](https://user-images.githubusercontent.com/16139977/41811630-48f57a6c-7724-11e8-8a5f-b3b8cca7021c.PNG)

**Comment by r9y9** [comment]
Are you running on window?

**Comment by r9y9** [comment]
Also if possible, please try to find the exact line of code that makes the problem stop.

**Comment by Ersho** [comment]
Yes, I am running on windows 10. I have debugged it by printing some random values, and printing does not work after line 701 in function train() in train.py file. This is the code 

``
soft_mask = guided_attentions(input_lengths, decoder_lengths,
                                              attn.size(-2),
                                              g=hparams.guided_attention_sigma)``

After this line nothing is printed anymore

I am running CUDA 9.0, cudnn 7.0 

The is my environment with all packages 

# packages in environment at C:\Users\*****\Anaconda3\envs\DvoicePy:
# Name                    Version                   Build  Channel
absl-py                   0.2.2                     <pip>
astor                     0.6.2                     <pip>
audioread                 2.1.6                     <pip>
bandmat                   0.7                       <pip>
blas                      1.0                         mkl
bleach                    1.5.0                     <pip>
certifi                   2018.4.16                py36_0
cffi                      1.11.5           py36h945400d_0
cuda90                    1.0                           0    pytorch
cycler                    0.10.0                    <pip>
Cython                    0.28.3                    <pip>
decorator                 4.3.0                     <pip>
docopt                    0.6.2                     <pip>
fastdtw                   0.3.2                     <pip>
gast                      0.2.0                     <pip>
grpcio                    1.12.1                    <pip>
html5lib                  0.9999999                 <pip>
icc_rt                    2017.0.4             h97af966_0
inflect                   0.3.1                     <pip>
intel-openmp              2018.0.3                      0
joblib                    0.11                      <pip>
kiwisolver                1.0.1                     <pip>
librosa                   0.6.1                     <pip>
llvmlite                  0.23.2                    <pip>
lws                       1.2                       <pip>
Markdown                  2.6.11                    <pip>
matplotlib                2.2.2                     <pip>
mkl                       2018.0.3                      1
mkl_fft                   1.0.1            py36h452e1ab_0
mkl_random                1.0.1            py36h9258bd6_0
nltk                      3.3                       <pip>
nnmnkwii                  0.0.14                    <pip>
numba                     0.38.1                    <pip>
numpy                     1.14.5                    <pip>
numpy                     1.14.5           py36h9fa60d3_0
numpy-base                1.14.5           py36h5c71026_0
Pillow                    5.1.0                     <pip>
pip                       10.0.1                   py36_0
protobuf                  3.6.0                     <pip>
pycparser                 2.18             py36hd053e01_1
pyparsing                 2.2.0                     <pip>
pysptk                    0.1.11                    <pip>
python                    3.6.5                h0c2934d_0
python-dateutil           2.7.3                     <pip>
pytorch                   0.4.0           py36_cuda90_cudnn7he774522_1  [cuda90]  pytorch
pytz                      2018.4                    <pip>
resampy                   0.2.1                     <pip>
scikit-learn              0.19.1                    <pip>
scipy                     1.1.0                     <pip>
setuptools                39.2.0                   py36_0
six                       1.11.0                    <pip>
sklearn                   0.0                       <pip>
tensorboard               1.8.0                     <pip>
tensorboardX              1.2                       <pip>
tensorflow-gpu            1.8.0                     <pip>
termcolor                 1.1.0                     <pip>
torchvision               0.2.1                     <pip>
tqdm                      4.23.4                    <pip>
Unidecode                 1.0.22                    <pip>
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
Werkzeug                  0.14.1                    <pip>
wheel                     0.31.1                   py36_0
wincertstore              0.2              py36h7fe50ca_0``

**Comment by ToxaDev** [comment]
I have a similar issue #95
After line 701, the python.exe process crashes

**Comment by Ersho** [comment]
If anyone has the same problem I managed to solve it by removing 

``
@jit(nopython=True)``

on line 551 

before function "guided_attention()"

**Comment by ToxaDev** [comment]
Python.exe crashes because my CPU does not support AVX instruction
Solved
