### ISSUE TITLE
training stopped at 0 iteration and python.exe crash

### ISSUE THREAD

**Issue by ToxaDev** [r9y9/deepvoice3_pytorch#95]
Preprocess pass fine, but training crash python.exe process at 0 iteration.
GPU load to 25% for one second while console show: 0it [00:00, ?it/s] and crash
No additional errors appears

I did try other versions of tensorflow from 1.3 to 1.8 and have same result
CUDA 8.0
cuDNN 6.0

![clip2net_180625153853](https://user-images.githubusercontent.com/11254917/41850628-e63a3a96-788d-11e8-9911-4c274c04dd80.png)

**Comment by r9y9** [comment]
Dup of #94. Maybe you are running on Window? I don't think the version of tensorflow matters.

**Comment by ToxaDev** [comment]
Windows 7 x64
Python 3.6.6 rc1

I think what issue #94 has little difference. He not got a crash of python.exe process
